export const ADVENTUREGAMES = [
    {
        plays: 122,
        language: "en",
        title: "Biker Lane",
        date_added: "07-17-2018",
        id: "6254874507345920",
        icon_large: "http://cdn.marketjs.net/games/biker-lane/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/biker-lane/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6254874507345920&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/biker-lane/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/biker-lane/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Test your motorbike riding skills",
        icon_small: "http://cdn.marketjs.net/games/biker-lane/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/biker-lane/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Control your bike rider to reach the flag. Boost, brake and tilt your bike left/right to navigate the tricky roads. Earn stars by completing the level in record time. Features: - Interactive tutorial - Use stars to unlock cool characters such as grandma biker, traffic police biker, punk biker, and pro biker. - Panning function to plan your routes - 20 challenging levels - Play repeatedly to get the best high score - Upbeat theme Motorcycle enthusiasts will love this game."
        },
        {
        plays: 13,
        language: "en",
        title: "Connect The Roads",
        date_added: "08-09-2019",
        id: "6327385315082240",
        icon_large: "http://cdn.marketjs.net/games/connect-the-roads/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/connect-the-roads/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6327385315082240&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/connect-the-roads/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/connect-the-roads/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Arrange the tiles to complete the road",
        icon_small: "http://cdn.marketjs.net/games/connect-the-roads/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/connect-the-roads/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Your car needs to get to work! Move the road tiles to complete the road. Can you get three stars for each level? Features: - Simple draggable tiles - Fun city theme - Turn grid on or off - 24 challenging levels guaranteed to twist your brain Fans of pipe games and picture sliders will love this game."
        },
        {
        plays: 26,
        language: "en",
        title: "Ski Slopes",
        date_added: "03-12-2021",
        id: "4878847326552064",
        icon_large: "http://subscription-cdn.marketjs.com/games/ski-slopes/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/ski-slopes/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4878847326552064&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/ski-slopes/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/ski-slopes/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Navigate mountain slopes and perform cool stunts",
        icon_small: "http://subscription-cdn.marketjs.com/games/ski-slopes/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/ski-slopes/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Ski down the mountain slopes. Tap to jump over obstacles. Perform cool backflips and frontflips in mid air. Collect coins to upgrade your snowman. Features: - Beautiful winter theme - Endless gameplay - Use coins to purchase upgrades in the store - Score points to unlock special snowman characters. Perfect for holidays, winter and seasonal campaigns such as Christmas."
        },
        {
        plays: 61,
        language: "en",
        title: "Wild West Shootout",
        date_added: "12-01-2017",
        id: "5689457298636800",
        icon_large: "http://cdn.marketjs.net/games/wild-west-shootout/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/wild-west-shootout/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5689457298636800&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/wild-west-shootout/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/wild-west-shootout/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Duel against bandits in this reflex game",
        icon_small: "http://cdn.marketjs.net/games/wild-west-shootout/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/wild-west-shootout/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Bandits are on the run! Play as the Sheriff, and hunt down the bandits one by one. Challenge each bandit to a duel, where the winner will the one with the quickest hands in the Wild West.</p> <p>Features:</p> <ul> <li>Cute graphics that cater to all ages</li> <li>Full fledged tutorial, to ease the learning curve</li> <li>Fun reflex-based game mechanic. How fast is your response time</li> <li>Innovative accuracy based duel system. The quicker your response time, the more accurate your shots become</li> <li>Shop to purchase upgrades, which include new weapons and armor</li> <li>Fun storyline and dialogue. Follow the Sheriff's journey, as he hunts down the bandits</li> </ul>"
        },
        {
        plays: 1,
        language: "en",
        title: "Oddbods Forest Run",
        date_added: "03-12-2021",
        id: "5651845423824896",
        icon_large: "http://subscription-cdn.marketjs.com/games/oddbods-forest-run-generic/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/oddbods-forest-run-generic/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5651845423824896&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/oddbods-forest-run-generic/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/oddbods-forest-run-generic/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Collect red Chili peppers and avoid obstacles",
        icon_small: "http://subscription-cdn.marketjs.com/games/oddbods-forest-run-generic/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/oddbods-forest-run-generic/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Fuse is on quest to collect red hot Chili peppers. Avoid obstacles such as spiders, boulders and tree frogs. How far can you go in this fun filled Oddbods endless runner game? Turbo charge your Oddbods experience with this game, featuring the lovable Fuse. Features: - Simple one-touch gameplay. Pick up your device and start playing! - Clear tutorial provided. - Stunning graphics - Fun Oddbods theme music - Great music - Increasingly difficult challenges. Every round is different. Easy to learn, hard to master. - Hours of addictive gameplay"
        },
        {
        plays: 18,
        language: "en",
        title: "Trapdoor",
        date_added: "07-17-2018",
        id: "5102826302734336",
        icon_large: "http://cdn.marketjs.net/games/trapdoor/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/trapdoor/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5102826302734336&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/trapdoor/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/trapdoor/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "A horror chat story game",
        icon_small: "http://cdn.marketjs.net/games/trapdoor/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/trapdoor/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Janie's car broke down. Embark on this chat story, as you uncover what happens next. Features: - innovative messenger based chat game - animated gifts and emoticons - simple one touch gameplay"
        },
        {
        plays: 14,
        language: "en",
        title: "Dumb Ways To Die 3: World Tour",
        date_added: "08-09-2019",
        id: "5117925977489408",
        icon_large: "http://cdn.marketjs.net/games/dumb-ways-to-die-3-world-tour/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/dumb-ways-to-die-3-world-tour/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5117925977489408&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/dumb-ways-to-die-3-world-tour/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/dumb-ways-to-die-3-world-tour/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Rebuild the great town of Dumbville",
        icon_small: "http://cdn.marketjs.net/games/dumb-ways-to-die-3-world-tour/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/dumb-ways-to-die-3-world-tour/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Play mini games featuring the characters from Dumb Ways to Die. Dumb Ways to Die is a worldwide brand with over 300 million downloads on Apple App Store and Google Play combined. Test your reflexes in this challenging series of mini games, where a milisecond can make the difference between winning and losing. Score coins for each challenge, and use the to repair the once great town of Dumbville. Features: - Extremely challenging levels. - Play as your favorite Beans: Stupe, Lax, Dippy, Dummkopf and Stumble, - Soar through the skies above Dumbville in a crazy plane. - Dash through the mighty Pyramids of Dumb-Gypt. - Collect unique outfits for all the Beans! - Explore a space station in Shuttle shift. - Send the Beans down the steep slopes of Dumb Peak."
        },
        {
        plays: 1,
        language: "en",
        title: "Jungle Dash Mania",
        date_added: "03-12-2021",
        id: "4829743904980992",
        icon_large: "http://subscription-cdn.marketjs.com/games/jungle-dash-mania/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/jungle-dash-mania/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4829743904980992&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/jungle-dash-mania/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/jungle-dash-mania/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Run away from big bear",
        icon_small: "http://subscription-cdn.marketjs.com/games/jungle-dash-mania/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/jungle-dash-mania/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Run away from the big forest bear. Jump above obstacles such as traps, rocks and tree stumps. Collect power ups to protect and boost yourself in this crazy jungle dash mania game. Features: - Jungle explorer theme - Cute but dangerous bear - Endless gameplay, great for competitions"
        },
        {
        plays: 83,
        language: "en",
        title: "X-Trench Run",
        date_added: "09-16-2019",
        id: "5645300149518336",
        icon_large: "http://cdn.marketjs.net/games/x-trench-run/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/x-trench-run/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5645300149518336&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/x-trench-run/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/x-trench-run/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Avoid obstacles and take out the turrets",
        icon_small: "http://cdn.marketjs.net/games/x-trench-run/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/x-trench-run/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Avoid obstacles and take out the turrets in this space simulation game. As the nation's star cadet, fly your x fighter wing deep into the enemy trench, disable enemy laser gates and hunt the boss. It's up to you to win this space war! Stay on course, don't crash, and use your intuition! Features: - Endless mode with increasing difficulty - Highly repetitive five star gameplay. Every round is different - Exciting boss fights. Earn your stars and stripes. - Fast and energetic music - Mobile and desktop friendly controls"
        },
        {
        plays: 95,
        language: "en",
        title: "Stupid Zombies",
        date_added: "03-12-2021",
        id: "5702495130091520",
        icon_large: "http://subscription-cdn.marketjs.com/games/stupid-zombies-1/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/stupid-zombies-1/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5702495130091520&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/stupid-zombies-1/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/stupid-zombies-1/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Hit zombie game with over 50 million downloads",
        icon_small: "http://subscription-cdn.marketjs.com/games/stupid-zombies-1/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/stupid-zombies-1/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "One man, one shotgun and a whole lot of zombies. You are humanity's last hope, and it's your job to keep them brainless. Adjust your shots and angles, and you watch your bullets ricochet from wall to wall, elegantly picking off each zombie's arms and limbs. Features: - 4 giant stages with over 360 challenging levels - Exciting zombie theme - Simple and innovative ricochet based gameplay. Defeat the stupid zombies with brains and ingenuity. - Realistic physics - Great zombie soundtrack"
        },
        {
        plays: 7,
        language: "en",
        title: "Ludo With Friends",
        date_added: "06-21-2019",
        id: "5147075350102016",
        icon_large: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5147075350102016&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Classic multiplayer board game for family and friends",
        icon_small: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Ludo with Friends is the modern version of the royal game of Pachisi. It's a game which was played among Indian kings and queens in ancient times. Roll the Ludo dice and move your tokens to reach the center of the Ludo board. Beat other opponents and become the king of Ludo in this multiplayer game. No complicated login screens. Just enter your username and play against the world. Play with your friends in a 2-player or 4-player mode. Features: - Chat with your friends in real-time - Feeling lazy? Use the autoplay function - Server side cheat detection - Play online against friends or offline against bots or computers"
        },
        {
        plays: 8,
        language: "en",
        title: "Oddbods Soccer Challenge",
        date_added: "08-09-2019",
        id: "5077215193595904",
        icon_large: "http://cdn.marketjs.net/games/oddbods-soccer-challenge/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/oddbods-soccer-challenge/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5077215193595904&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/oddbods-soccer-challenge/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/oddbods-soccer-challenge/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Kick the ball into the goal",
        icon_small: "http://cdn.marketjs.net/games/oddbods-soccer-challenge/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/oddbods-soccer-challenge/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Fancy a soccer game with your favourite Oddbods? Kick the ball into the goal, but beware! The mischievous Oddbods are here to stop you. Features: - Compete against Oddbods such as Fuse, Bubbles, Pogo, Zee, Slick, Jeff and Newt. - Fun Oddbods theme song - Over 60 levels more more to be added soon - Interactive tutorial Fans of soccer or football will love this game. If you're into the World Cup, English Premier League or UEFA Champions League, this game will be interesting too."
        },
        {
        plays: 3,
        language: "en",
        title: "High School Gossip",
        date_added: "03-12-2021",
        id: "5806807508320256",
        icon_large: "http://subscription-cdn.marketjs.com/games/high-school-gossip/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/high-school-gossip/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5806807508320256&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/high-school-gossip/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/high-school-gossip/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Chat story among high school friends",
        icon_small: "http://subscription-cdn.marketjs.com/games/high-school-gossip/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/high-school-gossip/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Rob just got back from his trip to Europe. Join the chat conversation with his friends, as they talk about Rob's Euro trip and the latest gossip at high school. This includes principal's hot new date, the most eligible guy in high school, creepy things, and more teenage drama. Features: - innovative messenger based chat game, optimized for smartphones - animated gifts and emoticons - simple one touch gameplay "
        },
        {
        plays: 9,
        language: "en",
        title: "Spidey Swing",
        date_added: "08-09-2019",
        id: "6266438017875968",
        icon_large: "http://cdn.marketjs.net/games/spidey-swing/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/spidey-swing/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6266438017875968&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/spidey-swing/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/spidey-swing/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Swing spidey to safety",
        icon_small: "http://cdn.marketjs.net/games/spidey-swing/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/spidey-swing/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "It's the adventures of Spidey. Shoot webs, grab on and swing like a spider pro. Avoid things such as sharp edges, rotating chainsaws, arrows, mace and other deadly objects. Keep the majority of your body parts intact, and get to the finish line. Keep our beloved Spidey alive! Features - Interactive tutorial - Touch, keyboard and mouse controls - City skyscraper theme - Over 24 extremely challenging levels. Test your spider-man skills. - Presence of blood and gore (can be turned off by request) - Fans of spiderman and marvel superheroes will love the game"
        },
        {
        plays: 26,
        language: "en",
        title: "Puppy Rescue",
        date_added: "07-17-2018",
        id: "5743804151758848",
        icon_large: "http://cdn.marketjs.net/games/puppy-rescue/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/puppy-rescue/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5743804151758848&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/puppy-rescue/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/puppy-rescue/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Save the puppies with your helicopter",
        icon_small: "http://cdn.marketjs.net/games/puppy-rescue/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/puppy-rescue/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Control your helicopter to save the puppies. Then, bring them to safety. Be careful, don't collide against other objects! Can you navigate quickly and get the 3 stars? Note: no animals are harmed in the making of this game. Features: - Interactive tutorial - Cute and helpless puppy dogs needing rescue - Play with keyboard , mouse or touch - Over 20 challenging levels - Each level gets progressively harder. Evade different objects such as hot air balloons, aircraft, moving platforms and more - Fun theme and music"
        },
        {
        plays: 6,
        language: "en",
        title: "Mango Piggy Piggy Hero",
        date_added: "09-16-2019",
        id: "5661041607311360",
        icon_large: "http://cdn.marketjs.net/games/mango-piggy-piggy-hero/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/mango-piggy-piggy-hero/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5661041607311360&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/mango-piggy-piggy-hero/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/mango-piggy-piggy-hero/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Save the world from evil",
        icon_small: "http://cdn.marketjs.net/games/mango-piggy-piggy-hero/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/mango-piggy-piggy-hero/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Mango Piggy Piggy is back with a brand new series. In his hero edition, control different superhero piggies, as you attempt to defend your town against the invasion of enemy robots. Launch your hero piggy against the enemy, in Angry Birds fashion. With Captain Piggy, throw your shield and watch as it bounces around the enemies, picking them off one by one. Use Iron Piggy to deal a huge amount of splash damage. Oh, did he mention Iron Piggy has lasers too? Use Thor Piggy to generate lightning with his mango-infused hammer. Shatter the ground and make your presence known. Features: - Excellent superhero theme and music. - Over 30 different levels per episode - Episodes 2, 3 and 4 coming soon - Challenging levels which require a combination of piggy heros - Fearsome enemy bosses - Interactive tutorial to learn the special abilities of each piggy - Full screen mode Fans of Marvel Avengers , Captain America, Iron Man and Thor will love this physics game."
        },
        {
        plays: 31,
        language: "en",
        title: "Giant Rabbit Run",
        date_added: "08-09-2019",
        id: "6304795129282560",
        icon_large: "http://cdn.marketjs.net/games/giant-rabbit-run/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/giant-rabbit-run/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6304795129282560&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/giant-rabbit-run/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/giant-rabbit-run/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Collect coins and easter eggs",
        icon_small: "http://cdn.marketjs.net/games/giant-rabbit-run/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/giant-rabbit-run/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Bunnie just got supersized. Switch lanes, jump and slide to avoid obstacles such as roadblocks and cars. Collect coins and easter eggs along the way. Use coins to purchase cool items, such as a skateboard, rocket pack and a magic carpet! How far can you run? Features: - Revolutionary first person 3D-like view - Fun theme and music - Easy and intuitive controls - Extremely cute rabbit ( happens to be a really big bunny ) - Endless runner - A shop with items to unlock Note: The desktop version uses keyboard controls. The mobile version uses easy touch/drag controls."
        },
        {
        plays: 51,
        language: "en",
        title: "Pilot Training",
        date_added: "07-17-2018",
        id: "5765827116662784",
        icon_large: "http://cdn.marketjs.net/games/pilot-training/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/pilot-training/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5765827116662784&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/pilot-training/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/pilot-training/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Train to be an airplane pilot",
        icon_small: "http://cdn.marketjs.net/games/pilot-training/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/pilot-training/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Attention junior pilot! You are training to be the best airplane pilot in the world.</p> <p>Embark on a variety of missions aimed at testing your handling and flexibility.</p> <p>Features:</p> <ul> <li>Fun theme suitable for all ages</li> <li>Pilot logbook for keeping scores</li> <li>Random missions include avoiding obstacles, tracking targets, collecting stars and harvesting fuel</li> <li>Easy and intuitive touch controls</li> <li>A shop to unlock different airplanes</li> </ul>"
        },
        {
        plays: 9,
        language: "en",
        title: "Montezuma Gems",
        date_added: "07-17-2018",
        id: "5589478376734720",
        icon_large: "http://cdn.marketjs.net/games/montezuma-gems/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/montezuma-gems/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5589478376734720&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/montezuma-gems/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/montezuma-gems/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Match gems to defeat the Montezuma warriors",
        icon_small: "http://cdn.marketjs.net/games/montezuma-gems/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/montezuma-gems/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Greetings adventurer! The time trials have begun. Match 3 or more colored gems to defeat the ancient Montezuma warriors protecting hidden treasures.</p> <p>Features:</p> <ul> <li>Interactive tutorial</li> <li>Compelling storyline with 5 different warriors to challenge</li> <li>Innovative match 3 swapping mechanic</li> <li>Powerups that enhance the gameplay, such as magic crystals, frozen gems, fireball gems and lightning crystals</li> <li>Progressive levels. The warriors are more difficult to overcome. They have more weapons at their disposal to challenge you.</li> </ul>"
        },
        {
        plays: 3,
        language: "en",
        title: "Ravensworth High School Story",
        date_added: "03-12-2021",
        id: "4805454388527104",
        icon_large: "http://subscription-cdn.marketjs.com/games/ravensworth-high-school-story/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/ravensworth-high-school-story/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4805454388527104&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/ravensworth-high-school-story/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/ravensworth-high-school-story/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Choose your own adventure",
        icon_small: "http://subscription-cdn.marketjs.com/games/ravensworth-high-school-story/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/ravensworth-high-school-story/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "You're Liz, and this is your first day at Ravensworth Academy, the elite high school for the country's best and brightest. Embark on a journey of self-discovery, family, friendship, camaraderie, love and drama in this latest high school themed visual novel. Features: - High school theme and graphics, suitable for a teen and young women audience - Linear and non-linear storyline - Collect stars, hearts and coins - Ability to resume story from previous saved point"
        },
        {
        plays: 8,
        language: "en",
        title: "Mountain Hop",
        date_added: "12-01-2017",
        id: "5745063384580096",
        icon_large: "http://cdn.marketjs.net/games/mountain-hop/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/mountain-hop/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5745063384580096&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/mountain-hop/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/mountain-hop/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Hop your away down the mountain",
        icon_small: "http://cdn.marketjs.net/games/mountain-hop/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/mountain-hop/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Hop your way down the mountain. Avoid obstacles such as poison potions, cracks, TNTs, and more. Collect stars along the way, and use them to unlock new characters.</p> <p>How high is your score?</p> <p>Features:</p> <ul> <li>Interactive tutorial. Learn how to play</li> <li>Unlock cute characters. Rabbits, sheeps, bears, tigers and elephants</li> <li>Avoid enemy characters such as the Grim reaper, lions, zombies and wolves.</li> <li>Take advantage of waterfalls to move faster</li> <li>Extremely fun and upbeat theme</li> </ul>"
        },
        {
        plays: 13,
        language: "en",
        title: "Flip Jump",
        date_added: "08-09-2019",
        id: "6357106452070400",
        icon_large: "http://cdn.marketjs.net/games/flip-jump/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/flip-jump/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6357106452070400&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/flip-jump/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/flip-jump/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How far can you jump?",
        icon_small: "http://cdn.marketjs.net/games/flip-jump/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/flip-jump/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap, hold and release to jump. Jump from one platform to the next. How far can you jump? Features: - Extremely cute and positive jumper game theme, great for brands - Simple, 1 touch gameplay - Unlock more characters by reaching certain milestones - Beautiful 3d artwork Fans of Tiao Yi Tiao and Bottle Flip will love this jumper game."
        },
        {
        plays: 8,
        language: "en",
        title: "Alpha Space Invasion",
        date_added: "07-17-2018",
        id: "5691331730997248",
        icon_large: "http://cdn.marketjs.net/games/alpha-space-invasion/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/alpha-space-invasion/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5691331730997248&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/alpha-space-invasion/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/alpha-space-invasion/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Fast paced space combat",
        icon_small: "http://cdn.marketjs.net/games/alpha-space-invasion/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/alpha-space-invasion/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Alpha sector is under invasion. Young pilot, your task is simple. Warp into the sector, and destroy enemy spacecraft before they destroy you. Avoid the asteroids and keep your shields high. Rake up as many hits as you can! Features: - Interactive tutorial - Simple controls (keyboard on desktop, touch controls on mobile) - Endless gameplay Fans of sci-fi movies such as Star Wars, Star Trek, Battlestar Galactica and Guardians of the Galaxy will love this game."
        },
        {
        plays: 5,
        language: "en",
        title: "Sky High",
        date_added: "07-17-2018",
        id: "5752553654452224",
        icon_large: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5752553654452224&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/banners/1300x500.png",
        banner_medium: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/banners/440x280.png",
        short_description: "Build your tower sky high",
        icon_small: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/banners/180x120.png",
        long_description: "How high can you build your tower? Use your timing to place the tower blocks correctly. Every inch of tower counts. Features: - Unlimited gameplay - Towers become more challenging to place as they get higher - Simple game controls: tap to place tower blocks - Use a variety of powerups such as Reverse, Repeat, Insurance, and Double Coins - Beautiful graphics and ancient greek theme"
        },
        {
        plays: 5,
        language: "en",
        title: "Temple Crossing",
        date_added: "12-01-2017",
        id: "5162027211292672",
        icon_large: "http://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5162027211292672&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Explore the temple, avoid the fall",
        icon_small: "http://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Guide the explorer into the temples. Build the bridge, and help him cross safely to the other side. Use your timing to build the perfect bridge. How many bridges can you cross?</p> <p></p> <p> Features: </p> <ul> <li>Tutorial to learn the ropes</li> <li>Tons of coins to collect</li> <li>Use coins to purchase powerups</li> <li>Powerups such as jump, second life and accurate eye</li> <li>A fun and relaxing theme</li> </ul> "
        },
        {
        plays: 2,
        language: "en",
        title: "Jumpee Land",
        date_added: "03-12-2021",
        id: "5034263486398464",
        icon_large: "http://subscription-cdn.marketjs.com/games/jumpee-land/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/jumpee-land/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5034263486398464&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/jumpee-land/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/jumpee-land/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Jump to the next platform",
        icon_small: "http://subscription-cdn.marketjs.com/games/jumpee-land/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/jumpee-land/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Play as a curious yellow 3d bird, jumping from one platform to the next. Avoid the lasers! Time your jumps, avoid traps such as breaking tiles, and face the ever changing landscape coming your way. How far can you go? Features: - Fun and quirky theme - Interactive tutorial - Unlock other animal characters"
        },
        {
        plays: 8,
        language: "en",
        title: "Puzzle Slide: Travel Edition",
        date_added: "09-16-2019",
        id: "5077274417168384",
        icon_large: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5077274417168384&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Discover your love of travelling",
        icon_small: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A picture slide game with a travel theme. Complete the puzzles in the shortest amount of time Solve puzzles of famous locations such as New York's Manhattan Bridge, The London Eye, Eiffel Tower of Paris, Forbidden City in Beijing, Tokyo Imperial Palace, Pyramids of Egypt, and more. Features - New-age, Instagram design for the millennial generation - Easy, medium and hard modes - Solve all kinds of puzzles from around the world - Simple design to encourage focus - Multiple puzzles to try - Relaxed environment "
        },
        {
        plays: 28,
        language: "en",
        title: "Escape From Aztec",
        date_added: "12-01-2017",
        id: "5666825723445248",
        icon_large: "http://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5666825723445248&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Run fast, avoid being caught",
        icon_small: "http://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "You just stole King Aztec's greatest treasure. Now you're being hunted. Run as fast as you can. Avoid tree trunks, boulders and ancient ruins. Switch lanes, jump and slide your way to freedom. Collect treasures along the way to purchase powerups. How far can you escape? Features: - 3D-like environment built with Aztec theme - Use Aztec coins to purchase powerups in the store - Use a variety of powerups such as invincibility, coin magnets, megaboost and extra lives"
        },
        {
        plays: 44,
        language: "en",
        title: "Koala Sling",
        date_added: "06-21-2019",
        id: "5188372165296128",
        icon_large: "http://cdn.marketjs.net/games/koala-sling/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/koala-sling/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5188372165296128&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/koala-sling/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/koala-sling/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How high can you go?",
        icon_small: "http://cdn.marketjs.net/games/koala-sling/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/koala-sling/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Drag and launch the Koala from one point to the next. Sling, bounce and swing your Koala to the highest peaks. Collect coins to unlock cool skins such Panda, Mr Crab, Octopus, Alien, and Mrs Yeti. Don't get burned! Don't get crushed. Features: - Fun and lively environment - Oh, did we say there's Koalas? - Challenging, endless gameplay. Great for competitive play with leaderboards"
        },
        {
        plays: 29,
        language: "en",
        title: "Shark Attack",
        date_added: "12-01-2017",
        id: "5662200312102912",
        icon_large: "http://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5662200312102912&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Live the life of a hungry shark",
        icon_small: "http://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Have you ever wondered what the life of a shark is like? Now you can live it. Swim around the ocean and hunt for your prey. Balance other aspects such as health, air and hunger. Avoid the jellyfish, bombs and fishing nets!</p> <p>A fun game for everyone, giving hours of gameplay.</p> <p>Features:</p> <ul> <li>Hunt other marine animals, including fish, octopus, starfish, crabs, and more</li> <li>Collect powerups for health, booster and energy</li> <li>Fun elements : attack boats, ships, divers and more</li> <li>Avoid the jelly fish, bombs and fishing nets</li> </ul>"
        },
        {
        plays: 11,
        language: "en",
        title: "Protect The Kingdom",
        date_added: "08-09-2019",
        id: "5757962879500288",
        icon_large: "http://cdn.marketjs.net/games/protect-the-kingdom/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/protect-the-kingdom/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5757962879500288&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/protect-the-kingdom/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/protect-the-kingdom/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Don't let the enemies reach your base!",
        icon_small: "http://cdn.marketjs.net/games/protect-the-kingdom/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/protect-the-kingdom/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap to remove the blocks. Remove the right blocks, in the right sequence to bring the totem to the safe spot. Protect the villagers from the anger of the volcano! Features: - a wide variety of blocks (wood,stone,glass,bouncers,voodoo). Use them to your advantage - additional cool items such as explosives - increasingly challenging levels - fun totem artwork - complete with native inhabitants and a volcano"
        },
        {
        plays: 3,
        language: "en",
        title: "Agent Curiosa Vs Rogue Robots",
        date_added: "08-09-2019",
        id: "5644660766670848",
        icon_large: "http://cdn.marketjs.net/games/agent-curiosa-vs-rogue-robots/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/agent-curiosa-vs-rogue-robots/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5644660766670848&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/agent-curiosa-vs-rogue-robots/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/agent-curiosa-vs-rogue-robots/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Stop the robots from overtaking Earth!",
        icon_small: "http://cdn.marketjs.net/games/agent-curiosa-vs-rogue-robots/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/agent-curiosa-vs-rogue-robots/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "The robots have gone rogue! It's up to teen hacker, Agent Curiosa to save the world. Armed with your DIY electric zapper, zap these robots out of existence! Features: - Over 30 challenging levels. Fight robots of all kinds. - Face big, bad drones in boss levels. - Collect items such as extra bonus scores, invisibility, extra life and score boost. - Interactive tutorial. - Techy theme suitable for tweens and teens alike."
        },
        {
        plays: 24,
        language: "en",
        title: "Santa City Run",
        date_added: "07-17-2018",
        id: "5160769706524672",
        icon_large: "http://cdn.marketjs.net/games/santa-city-run/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/santa-city-run/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5160769706524672&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/santa-city-run/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/santa-city-run/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Ho ho ho! Santa Claus is on the run",
        icon_small: "http://cdn.marketjs.net/games/santa-city-run/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/santa-city-run/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Guide Santa along the city streets, avoiding obstacles along the way. Jump over cars, side step traffic codes and avoid blockades. Boost your points by collecting Christmas gifts.</p> <p>How many points can you score?</p> <p>Features:</p> <ul> <li>Christmas theme suitable for families</li> <li>Interactive tutorial</li> <li>3D like environment</li> <li>Intuitive controls. Use the keyboard for desktop devices. Use touch for smartphones and tablets</li> <li>Collect elves to gain a temporary bubble shield</li> <li>A cool shop to purchase upgrades for Santa. Includes a hoverboard, segway, skateboard and a rocket booster</li> </ul>"
        },
        {
        plays: 9,
        language: "en",
        title: "Crown and Ambition",
        date_added: "03-12-2021",
        id: "4674507949211648",
        icon_large: "http://subscription-cdn.marketjs.com/games/crown-and-ambition/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/crown-and-ambition/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4674507949211648&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/crown-and-ambition/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/crown-and-ambition/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Choose your own adventure",
        icon_small: "http://subscription-cdn.marketjs.com/games/crown-and-ambition/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/crown-and-ambition/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Follow the adventures of Captain Kirana Asha, as she uncovers dark forces trying to overthrow the beloved King Adler. With your trusty sidekick Evans, choose your actions wisely, as they determine the fate of your kingdom. Will you unravel this mystery and punish the perpetrators? Features: - Interactive story. Take the driver's seat, and choose your own adventure - Deep storyline with plenty of choices. Every action you take will determine the outcome of the game - Auto play mode - Earn points for making the right decisions"
        },
        {
        plays: 29,
        language: "en",
        title: "Zombie Survival",
        date_added: "12-01-2017",
        id: "5650560950730752",
        icon_large: "http://cdn.marketjs.net/games/zombie-survival/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/zombie-survival/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5650560950730752&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/zombie-survival/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/zombie-survival/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How many days can you last?",
        icon_small: "http://cdn.marketjs.net/games/zombie-survival/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/zombie-survival/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A strange virus outbreak turned your friends into zombies. Armed with a basic pistol, make your way through hordes of zombies. How many days can you survive, before you become one of them? Features: - 3D like isometric graphics - Collect coins with each zombie kill - Multiple weapons to purchase. Try the machine gun, shotgun, rifle and laser gun - Fun stats to review after each day - 3 different gameplay modes: Survival, Hard Point and Nuke - Tutorial to learn the ropes - Yes, you can blow up barrels to burn the zombies"
        },
        {
        plays: 30,
        language: "en",
        title: "Santa Airlines",
        date_added: "06-21-2019",
        id: "6259230254301184",
        icon_large: "http://cdn.marketjs.net/games/santa-airlines/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/santa-airlines/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6259230254301184&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/santa-airlines/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/santa-airlines/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Forget reindeers, this Santa flies a plane",
        icon_small: "http://cdn.marketjs.net/games/santa-airlines/localization/en/media/graphics/promo/icons/72x72.png",
        banner_small: "http://cdn.marketjs.net/games/santa-airlines/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>21st century Santa now delivers presents via his Skybus DEC25. Help Santa navigate the skies with his cool airplane.</p> <p>Collect presents, boosters and rescue kids along the way. Naughty or nice, find out yourself!</p> <p>Features:</p> <ul> <li> christmas theme</li> <li> cool santa in pilot attire</li> <li> cloud obstacles</li> <li> interactive tutorial</li> <li> extremely easy and intuitive touch controls</li> <li> cool collectibles and power ups. Time to get this xmas party started!</li> </ul>"
        },
        {
        plays: 1,
        language: "en",
        title: "Cooking Love",
        date_added: "03-12-2021",
        id: "6070817268957184",
        icon_large: "http://subscription-cdn.marketjs.com/games/cooking-love/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/cooking-love/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6070817268957184&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/cooking-love/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/cooking-love/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Discover food, friendship and love. It's your story, your life!",
        icon_small: "http://subscription-cdn.marketjs.com/games/cooking-love/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/cooking-love/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "You just arrived in New York, to pursue your dream of becoming a chef. Your plan? Work for the famed and attractive chef extraordinaire, Giovanni van Damme to gain experience. Work your way up the culinary ladder to become Manhattan's hottest chef, in this episode driven interactive story novel. Discover food, friendship and love. Stumble through life and live the ups and downs of what the Big Apple has to offer. Make choices that affect how others perceive you. Features: - Beautiful characters with personality. - Emotional scenes and storyline - 5 full episodes (chapters) available - Wear cool outfits - Send text messages to your friends - Wide screen responsive format suitable for all modern devices. - Ability to continue the story at any time. - Insert your own name into the story, and be your own lead character. - Need a better view of the characters? Activate the full screen mode."
        },
        {
        plays: 5,
        language: "en",
        title: "Red Outpost",
        date_added: "07-17-2018",
        id: "5092570659028992",
        icon_large: "http://cdn.marketjs.net/games/red-outpost/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/red-outpost/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5092570659028992&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/red-outpost/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/red-outpost/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Build and grow your martian colony",
        icon_small: "http://cdn.marketjs.net/games/red-outpost/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/red-outpost/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>We have finally landed on Mars! Recruit astronauts from Earth to build your martian outpost.</p> <p>Harvest crops from the habitat, generate solar energy, mine martian rocks, and discover new technologies along the way. With proper management techniques, grow and thrive!</p> <p>Features:</p> <ul> <li>Fun martian theme, suitable for science and space exploration enthusiasts</li> <li>Endless gameplay</li> <li>A variety of new upgrades and technologies</li> <li>Ability to save and load games</li> <li>Interactive tutorial</li> </ul>"
        },
        {
        plays: 36,
        language: "en",
        title: "Team Kaboom",
        date_added: "07-17-2018",
        id: "6276985670074368",
        icon_large: "http://cdn.marketjs.net/games/new-team-kaboom/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/new-team-kaboom/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6276985670074368&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/new-team-kaboom/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/new-team-kaboom/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Blast enemies with cool weapons",
        icon_small: "http://cdn.marketjs.net/games/new-team-kaboom/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/new-team-kaboom/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Attention soldier! Your goal is to blast enemies, and avoid getting killed. Avoid letting the enemies escape! If they escape, they'll come back faster and stronger. Features: - 3 different maps - 5 cool characters. Each character holds a cool weapon. Rifles, machine guns, dynamites, knives, and oh, did we mention a rocket launcher? - Fun pixel theme - Intuitive controls for mobile and desktop"
        },
        {
        plays: 13,
        language: "en",
        title: "Boat Dash",
        date_added: "12-01-2017",
        id: "6241650187698176",
        icon_large: "http://cdn.marketjs.net/games/boat-dash/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/boat-dash/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6241650187698176&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/boat-dash/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/boat-dash/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Ride your boat and avoid obstacles",
        icon_small: "http://cdn.marketjs.net/games/boat-dash/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/boat-dash/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>You're on a fun boat ride. Enjoy beautiful views along the way as you try to avoid obstacles.</p> <p>How far can you ride?</p> <p>Features:</p> <ul> <li>Collect powerups such as bubbles and star badges</li> <li>Fun theme and audio</li> <li>5 different boat types. Try the inflatable raft, speed boat, hovercraft, yacht and cargo ship.</li> <ul>"
        },
        {
        plays: 10,
        language: "en",
        title: "Adventure Craft",
        date_added: "07-17-2018",
        id: "5376940124930048",
        icon_large: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5376940124930048&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Mine similar blocks to score points",
        icon_small: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Match similar blocks within the allocated time to progress. Click and drag to form giant blockchains.</p> <p>If you like voxels and minecraft, then this game is definitely for you.</p> <p>Features:</p> <ul> <li>Voxel based match 3 theme</li> <li>Innovative click and drag mechanic to build giant block chains</li> <li>20 challenging levels</li> <li>Tutorial to learn the ropes</li> <li>Good game pace and music</li> </ul>"
        },
        {
        plays: 8,
        language: "en",
        title: "Corporate Overlord",
        date_added: "07-17-2018",
        id: "5980808080785408",
        icon_large: "http://cdn.marketjs.net/games/corporate-overlord/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/corporate-overlord/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5980808080785408&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/corporate-overlord/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/corporate-overlord/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Build your evil corporation",
        icon_small: "http://cdn.marketjs.net/games/corporate-overlord/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/corporate-overlord/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Welcome to the corporate world. Build your evil corporation, generate massive wealth and dominate the world!</p> <p>Features:</p> <ul> <li>Build cool structures such as quantum supercomputer labs and chemical labs</li> <li>Research important technologies including spy drones, instant freezers, droids, and even zombie servants</li> <li>Invest in structures to generate returns</li> <li>Ability to generate different corporate names</li> <li>Interactive tutorial</li> <li>Beware of disaster events! Manage them (and your stress level) appropriately.</li> </ul>"
        },
        {
        plays: 6,
        language: "en",
        title: "Chat Stories",
        date_added: "09-16-2019",
        id: "5170014438031360",
        icon_large: "http://cdn.marketjs.net/games/chat-stories/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/chat-stories/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5170014438031360&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/chat-stories/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/chat-stories/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Heartwarming stories for teens and adults",
        icon_small: "http://cdn.marketjs.net/games/chat-stories/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/chat-stories/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Heartwarming and emotional stories for teens and adults, presented in an SMS messenger style. Read engaging stories such as - Secret Admirer : a girl gets a text from an unknown number - Lost Dog : two people connect over a lost dog - Pulled Over : a party girl is being pulled over by the police late at night - Push and Pull : a fun and quirky story about the push and pull of love - Friendzone : will two close friends date, or remain friends? - Break Up : a comforting and heartwarming story about a post-breakup Storytelling has never been this fun! Features: - innovative messenger based chat game, optimized for smartphones. Make your users addicted to stories! - animated gifts, emojis and emoticons. - simple one touch gameplay - interesting stories guaranteed to get your users hooked - new stories added each month"
        },
        {
        plays: 8,
        language: "en",
        title: "Bubble Pop Adventures",
        date_added: "12-01-2017",
        id: "6270884151033856",
        icon_large: "http://cdn.marketjs.net/games/bubble-pop-adventures/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/bubble-pop-adventures/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6270884151033856&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/bubble-pop-adventures/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/bubble-pop-adventures/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Pop bubbles to rescue baby mushrooms",
        icon_small: "http://cdn.marketjs.net/games/bubble-pop-adventures/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/bubble-pop-adventures/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Mama mushroom needs your help! Rescue trapped baby mushrooms by matching the correct bubbles.</p> <p>Features:</p> <ul> <li>Solve bubble sets using a variety of tactics</li> <li>Score combo points for using elegant solutions</li> <li>Play with different colored bubbles and special bubbles</li> <li>24 challenging levels</li> <li>Fun and uplifting theme, suitable for families</li> </ul>"
        },
        {
        plays: 18,
        language: "en",
        title: "Street Fight",
        date_added: "12-01-2017",
        id: "4896322817622016",
        icon_large: "http://cdn.marketjs.net/games/street-fight/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/street-fight/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4896322817622016&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/street-fight/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/street-fight/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Fight on the streets. Survive and thrive.",
        icon_small: "http://cdn.marketjs.net/games/street-fight/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/street-fight/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Play as a young dashing hero. Fight enemy thugs on the street. Throw your combinations and knock them out!</p> <p>Collect coins from your wins, use them to purchase cool powerups.</p> <p> Features: </p> <ul> <li>Intuitive touch and drag controls for mobile</li> <li>Intuitive click/move mouse combos on desktop</li> <li>10 different enemy characters. Each character has a unique skillset and AI</li> <li>10 different enemy characters. Each character has a unique skillset and AI</li> <li>5 different attack combinations</li> <li>3 different maps: Sunset Avenue, Frozen Overpass and Mean Street</li> <li>A shop to purchase power ups</li> </ul>"
        },
        {
        plays: 22,
        language: "en",
        title: "Hop Stars",
        date_added: "06-21-2019",
        id: "5204128319930368",
        icon_large: "http://cdn.marketjs.net/games/hop-stars/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/hop-stars/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5204128319930368&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/hop-stars/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/hop-stars/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How many hops can you make?",
        icon_small: "http://cdn.marketjs.net/games/hop-stars/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/hop-stars/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Hop on as many platforms as possible. Earn points for every successful hop. Bounce your ball exactly in the middle of the platform, to earn combo points. An extremely addictive hypercasual game. Features: - Interactive tutorial - Collect coins to unlock different balls - Fun endless theme. Play for hours while you compete with friends - Great theme and music"
        },
        {
        plays: 1,
        language: "en",
        title: "Connect The Gems",
        date_added: "03-12-2021",
        id: "5684510730485760",
        icon_large: "http://subscription-cdn.marketjs.com/games/connect-the-gems/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/connect-the-gems/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5684510730485760&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/connect-the-gems/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/connect-the-gems/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Can you complete all levels?",
        icon_small: "http://subscription-cdn.marketjs.com/games/connect-the-gems/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/connect-the-gems/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Connect gems of the same color. Meet the minimum gems required for each level. Twist and turn your brain to match 3 or more gems. Don't run out of moves! Features: - Interactive tutorial, guided by 2 ancient owls - Over 36 challenging levels - Learn new matching abilities along the way - Encounter tricky match-3 puzzle sets - Fun and uplifting theme suitable for everyone"
        },
        {
        plays: 46,
        language: "en",
        title: "Hidden Objects - Mysterious Artifacts",
        date_added: "12-01-2017",
        id: "5133511581237248",
        icon_large: "http://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5133511581237248&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Search for mysterious hidden artifacts",
        icon_small: "http://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Billy the Treasure Hunter is back! Help Billy uncover ancient artifacts in this hidden object game. Discover beautiful hidden objects in different settings.</p> <p> Features: </p> <ul> <li>Mysterious ancient theme</li> <li>Over 50 objects to discover - Jewels, ancient scrolls, magic staffs and more</li> <li>Need help? Use hints by earning hints points (keys)</li> <li>Complete tutorial system</li> <li>Over 9 challenging levels in 3 different settings</li> </ul>"
        },
        {
        plays: 5,
        language: "en",
        title: "Swing Forward",
        date_added: "12-01-2017",
        id: "5183400629501952",
        icon_large: "http://cdn.marketjs.net/games/swing-forward/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/swing-forward/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5183400629501952&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/swing-forward/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/swing-forward/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Train your estimation skills",
        icon_small: "http://cdn.marketjs.net/games/swing-forward/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/swing-forward/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Estimate the length of the rope you need, to swing to the next platform. How far can you go? It's easy the first few swings, but then it gets difficult. Be prepared! Features: - Interactive tutorial - Simple one touch gameplay - Collect gems to unlock cute characters - Fun and cute environment - Local high score to track your performance"
        },
        {
        plays: 13,
        language: "en",
        title: "Spore Hunter",
        date_added: "08-09-2019",
        id: "5183609855016960",
        icon_large: "http://cdn.marketjs.net/games/spore-hunter/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/spore-hunter/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5183609855016960&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/spore-hunter/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/spore-hunter/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Defend your spaceship against pesky space spores",
        icon_small: "http://cdn.marketjs.net/games/spore-hunter/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/spore-hunter/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap and hold to attack the incoming space spores. You only have 3 lives. Features: - Cool space theme - Tap to repair your ship - Collect powerups to boost your score"
        }
]