export const BOARDGAMES = [
        {
        plays: 8,
        language: "en",
        title: "Poker with Buddies",
        date_added: "03-12-2021",
        id: "4947100933554176",
        icon_large: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4947100933554176&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Texas hold em poker with friends",
        icon_small: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Play Texas Hold 'Em poker with anyone on the internet. Place virtual chips on the table, and try to outsmart the other players and the dealer. Meet new friends online over casual poker games. Want to only play with your friends? No problem. Set up a private room with a password. Features: - Up to 6 players in a room - Unlimited rooms - Chat functionality - Play if bots or AI, if humans are not present - Automatic room assignment - Private rooms with password is now possible - Pick a cool avatar before joining the room Fans of Texas Holdem Poker will appreciate this game."
        },
        {
        plays: 2,
        language: "en",
        title: "Onet Connect",
        date_added: "03-12-2021",
        id: "6463408804200448",
        icon_large: "http://subscription-cdn.marketjs.com/games/onet-connect/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/onet-connect/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6463408804200448&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/onet-connect/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/onet-connect/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Match fruits of the same type",
        icon_small: "http://subscription-cdn.marketjs.com/games/onet-connect/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/onet-connect/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Connect fruit tiles of the same image. A game of creativity, problem solving and cognitive enhancement. Use fewer than 3 lines. Only 2 tiles per connection. This is not a match 3 game, but rather a match 2 game that focuses on spatial training and puzzle solving. Features - 3 difficulty levels. Easy, medium and hard - Randomized set, every time you play. Ensure unlimited gameplay. - Casual theme, suitable for all ages and families - Ability to shuffle the set - Huge set for long periods of gameplay. Great for focus and leisurely problem solving."
        },
        {
        plays: 10,
        language: "en",
        title: "Carrom with Buddies",
        date_added: "03-12-2021",
        id: "5345886365286400",
        icon_large: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5345886365286400&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Play carrom with your friends online",
        icon_small: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Revive your childhood dreams by playing Carrom with your buddies. Cover the Queen (Pot the Queen, followed by a Carrommen). Pot all your Karrom pieces with the Queen, covered before the last Carom piece. Features: - Beautiful board and Karom pieces - 2 player mode - Play with either a human or a bot - Private mode where you can play with a designated password - Realistic physics - Elegantly designed notifications - Clean and modern design - Emojis to express yourself"
        },
        {
        plays: 2,
        language: "en",
        title: "Battleships Ready Go!",
        date_added: "03-12-2021",
        id: "5683524616060928",
        icon_large: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5683524616060928&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Sink the enemy ships in naval warfare",
        icon_small: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Battleships Ready Go is a guessing war game. Place your ships strategically across the open sea. Then, try to sink the enemy ships, before own own navy ships are sunk. Features: - Interactive tutorial - Fast paced music and gameplay - Millions of battleship arrangements, for hours of gameplay - Clever AI to compete against"
        },
        {
        plays: 3,
        language: "en",
        title: "Snakes and Ladders",
        date_added: "03-12-2021",
        id: "6320790204055552",
        icon_large: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6320790204055552&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Roll the dice to win. Play with your friends online!",
        icon_small: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Your life is represented by ladders (opportunities) and snakes (challenges). Roll the dice to navigate your pieces across the board in this fun multiplayer game. Arrive at a ladder, and advance faster. Arrive at a snake, and be transferred back a few steps. Who will win in this game of chance? Features: - Play with 2 or 4 people in a room. - Chat and make friends in this multiplayer casual game. - Easy to pick up and play. Anybody can win! - Plenty of avatars to choose from. - No friends? Play with the computer - Custom username. - Responsive and Full screen mode available."
        },
        {
        plays: 1,
        language: "en",
        title: "Mine Sweeper",
        date_added: "03-12-2021",
        id: "5671485705289728",
        icon_large: "http://subscription-cdn.marketjs.com/games/mine-sweeper/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/mine-sweeper/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5671485705289728&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/mine-sweeper/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/mine-sweeper/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Clear the board without detonating the mine",
        icon_small: "http://subscription-cdn.marketjs.com/games/mine-sweeper/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/mine-sweeper/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A mine field is waiting to be cleared. Use your wits, memory and bravado to unravel each square. If you detonate a single mine, it's game over! Features: - Clean and simple design - 3 difficulty levels - Endless gameplay with random mines generation"
        },
        {
        plays: 5,
        language: "en",
        title: "Sumo Push Push",
        date_added: "03-12-2021",
        id: "5386651997044736",
        icon_large: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5386651997044736&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Attack and defend lanes with Sumo warriors",
        icon_small: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap on the dirt lanes, to launch your Sumo heroes forward. Overpower your opponents with clever placement of Sumo warriors. Make use of different Sumo weight classes to win lane control, in this fast paced multiplayer PvP game. Features: - Exciting Player vs Player (PvP) game mechanic - Sumo theme with Sumo warriors and hero theme - Random selection of opponents in this multiplayer game - Play with your friends in real-time - Taunt your friends using emoticons - Chat with your friends while playing"
        },
        {
        plays: 8,
        language: "en",
        title: "London Jigsaw Puzzle",
        date_added: "03-12-2021",
        id: "4827298726412288",
        icon_large: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4827298726412288&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Discover London via jigsaw puzzles",
        icon_small: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Arrange the jigsaw pieces of famous landmarks in London. Solve puzzles of famous sights such as the London Eye, Big Ben, Tower of London, Buckingham Palace, Hyde Park, Trafalgar Square, Westminster Abbey and more. Features: - Modern instagram type design, suitable for a young and millennial audience. - Hints system. - Zoom function to zoom out. - Modify the number of pieces each row or column. - Select different backgrounds to work on. - Peaceful theme and music."
        },
        {
        plays: 20,
        language: "en",
        title: "Dominoes",
        date_added: "03-12-2021",
        id: "6204939769479168",
        icon_large: "http://subscription-cdn.marketjs.com/games/dominoes/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/dominoes/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6204939769479168&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/dominoes/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/dominoes/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Simple and minimalist domino game",
        icon_small: "http://subscription-cdn.marketjs.com/games/dominoes/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/dominoes/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Draw dominoes: Every round, match tiles until your opponent is unable to move. If you have no possible moves, draw a domino until you can match a tile. If there are no dominoes left, pass your turn until you can. Reach 100 points to win. Block dominoes: The same as Draw Dominoes. The main difference is, if you have no possible moves, pass your turn until you can match a tile. Reach 100 points to win. Features: - Clean and minimalist design - No background music, to avoid any distraction - Clever AI - Touch based, drag and drop controls"
        },
        {
        plays: 1,
        language: "en",
        title: "Holiday Crossword",
        date_added: "03-12-2021",
        id: "6498977928183808",
        icon_large: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6498977928183808&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Travel and learn while solving crossword puzzles.",
        icon_small: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Solve holiday themed crossword puzzles involving various topics such as cities, food, celebrations and gift ideas. Features: - Full screen mode - Easy to use cross word puzzle. Regardless of device, play the same crossword puzzle as everybody else - Easy selection of puzzle grid to insert answers - Virtual keyboard for mobile and tablet users. Easily enter your answers to solve the puzzles - Random puzzles generated from a pool of questions and answers - Relaxing theme, suitable for everyone Note: if you'd like different themes and questions, please contact us."
        }
]