export const EDUCATIONALGAMES = [
        {
        plays: 0,
        language: "en",
        title: "Spot The Patterns",
        date_added: "03-12-2021",
        id: "4817822417944576",
        icon_large: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4817822417944576&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Predict the next object intelligently",
        icon_small: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A good cognitive training game. Predict the next object based on the previous pattern. Features: - Hint system - 3 different levels. Easy, Medium and Hard - Fun and vibrant theme which encourages learning This game is perfect for schools, preschool, families and even seniors."
        },
        {
        plays: 1,
        language: "en",
        title: "Typing Fighter",
        date_added: "03-12-2021",
        id: "6749550397095936",
        icon_large: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6749550397095936&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Type fast and fight hard",
        icon_small: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Type fast, type accurate and fight hard in this innovative street fighter style typing game. Charge up your typing and deliver killer power moves. Get inspired by motivational phrases and quotes while you type. Fight against a variety of opponents. Features: - Beautifully designed street fight urban setting - Fluid character animations - Over 200 motivational quotes and phrases to keep you going"
        },
        {
        plays: 1,
        language: "en",
        title: "Arty Mouse: Sticker Book",
        date_added: "03-12-2021",
        id: "5962400684572672",
        icon_large: "http://subscription-cdn.marketjs.com/games/arty-mouse-sticker-book/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/arty-mouse-sticker-book/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5962400684572672&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/arty-mouse-sticker-book/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/arty-mouse-sticker-book/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "A sticker activity book for kids",
        icon_small: "http://subscription-cdn.marketjs.com/games/arty-mouse-sticker-book/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/arty-mouse-sticker-book/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Now, your kids can express themselves through art. Place your favourite Arty Mouse stickers onto the board, decorate them as you wish. Drag and drop, resize and reposition them to your hearts content. Need to erase a sticker? No problem. Create millions of sticker combinations using different Arty Mouse characters, objects and backgrounds. Work with Scribble the dog, Stripy the cat, Dot the bear, Rainbow Birds, Spiro the snail, and more characters. Features: - Simple tutorial to get started - Free form activity for kids to encourage creativity - Over 120 sticker items ranging from animals, to party hats, glasses, sun, moon, sandcastles, tractors, rockets and more. - Fun and positive theme - Ability to enlarge the screen for easier previews"
        },
        {
        plays: 0,
        language: "en",
        title: "Trivia Quiz",
        date_added: "03-12-2021",
        id: "5117539865591808",
        icon_large: "http://subscription-cdn.marketjs.com/games/trivia-quiz/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/trivia-quiz/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5117539865591808&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/trivia-quiz/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/trivia-quiz/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How many questions can you answer correctly?",
        icon_small: "http://subscription-cdn.marketjs.com/games/trivia-quiz/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/trivia-quiz/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Test your general knowledge in this trivia quiz game. How many questions can you answer correctly? Features: - Simple, clean and welcoming theme - Easy to configure Trivia Quiz. Let us know what you need, and we'll customize it for you. - Question separated into different difficulty levels (easy questions first, followed by more challenging questions) - 30 randomly rotated questions per round - Over 100 different questions in the pool - Fullscreen mode"
        },
        {
        plays: 1,
        language: "en",
        title: "Millionaire Quiz HD",
        date_added: "03-12-2021",
        id: "4807660676317184",
        icon_large: "http://subscription-cdn.marketjs.com/games/millionaire-quiz-new/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/millionaire-quiz-new/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4807660676317184&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/millionaire-quiz-new/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/millionaire-quiz-new/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Enter the game show, win a million dollars.",
        icon_small: "http://subscription-cdn.marketjs.com/games/millionaire-quiz-new/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/millionaire-quiz-new/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "How good is your trivia knowledge? Put your skills to test against the ultimate game show, Millionaire Quiz! Answer trivia questions ranging from Science, Technology, Sports, Music and Health. Features: - NEW: HD version - Fun game show theme. Live the glitz and glamor of a contestant - Entertaining game show host - Stuck? Use the 3 lifelines ( call a friend, eliminate other answers, and ask the audience) - Challenging questions. They only get tougher the farther you get"
        },
        {
        plays: 11,
        language: "en",
        title: "Sort the Trash",
        date_added: "03-12-2021",
        id: "6317311196659712",
        icon_large: "http://subscription-cdn.marketjs.com/games/sort-the-trash/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/sort-the-trash/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6317311196659712&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/sort-the-trash/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/sort-the-trash/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Collect recyclable items, avoid contaminators",
        icon_small: "http://subscription-cdn.marketjs.com/games/sort-the-trash/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/sort-the-trash/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Protect the environment by learning how to recycle correctly. Collect items that can be recycled only. Avoid collecting contaminators such as organic waste, disposable coffee cups, plastic straws, ceramic dishware and lithium ion batteries. Go green and save the Earth. Start becoming eco-friendly today! Features: - Simple elegant design - Responsive design - Positive them with recycling facts"
        },
        {
        plays: 8,
        language: "en",
        title: "Wheel of Rewards",
        date_added: "03-12-2021",
        id: "5286446115061760",
        icon_large: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5286446115061760&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Spin the wheel, guess the letter and solve the puzzle",
        icon_small: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Spin the wheel, guess letter and solve the puzzle! Earn cash from your spins, to purchase more vowels. Uncover the puzzle letter by letter, and solve it to win bonus rewards. Try not to go bankrupt or run out of lives! Your fortune depends on your ability to solve the puzzle. Answer questions from a variety of topics such as: - Things People Worry About - What People Do At 3 AM - What Happens At Work - Special Occasions - Common Excuses to Skip Work and many other thought-provoking topics! Features: - Vibrant and fresh game show theme - Over 200 puzzles to solve - 10 lives to start with - Full screen mode"
        },
        {
        plays: 2,
        language: "en",
        title: "Positive Reinforcement",
        date_added: "03-12-2021",
        id: "5169664796655616",
        icon_large: "http://subscription-cdn.marketjs.com/games/positive-reinforcement/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/positive-reinforcement/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5169664796655616&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/positive-reinforcement/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/positive-reinforcement/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Collect positive words, avoid negative ones",
        icon_small: "http://subscription-cdn.marketjs.com/games/positive-reinforcement/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/positive-reinforcement/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "These are tough times, but we can all do something to stay positive. Drag and move the basket to collect positive words. Avoid negative words at all cost! Learn new positive words and expand your vocabulary at the same time. Features: - Upbeat and modern theme - Great inspiration music - Easy controls for desktop and mobile users This game is great for businesses exploring digital therapeutics, wellness and corporate engagement training programmes."
        },
        {
        plays: 1,
        language: "en",
        title: "Numbers Challenge",
        date_added: "03-12-2021",
        id: "6375179035869184",
        icon_large: "http://subscription-cdn.marketjs.com/games/numbers-challenge/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/numbers-challenge/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6375179035869184&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/numbers-challenge/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/numbers-challenge/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Determine which side is greater",
        icon_small: "http://subscription-cdn.marketjs.com/games/numbers-challenge/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/numbers-challenge/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Which side is greater? Left, right or are they equal? Numbers Challenge is a new and exciting cognitive math based game. Answer 5 questions in a row correctly, to move up the level. Miss one, and the game is over at the end of the level. Features: - Easy to start. The math gets complicated the further you go - Peaceful theme, suitable for concentration - Tough and tricky questions - Accuracy stats for math geeks"
        },
        {
        plays: 1,
        language: "en",
        title: "Holiday Crossword",
        date_added: "03-12-2021",
        id: "6498977928183808",
        icon_large: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6498977928183808&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Travel and learn while solving crossword puzzles.",
        icon_small: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Solve holiday themed crossword puzzles involving various topics such as cities, food, celebrations and gift ideas. Features: - Full screen mode - Easy to use cross word puzzle. Regardless of device, play the same crossword puzzle as everybody else - Easy selection of puzzle grid to insert answers - Virtual keyboard for mobile and tablet users. Easily enter your answers to solve the puzzles - Random puzzles generated from a pool of questions and answers - Relaxing theme, suitable for everyone Note: if you'd like different themes and questions, please contact us."
        }
]