export const FEATUREDGAMES:any = [
                {       
                genres: "Family",
                screenshot2_small: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 8,
                language: "en",
                title: "Pop Star Dentist 2",
                date_added: "12-01-2017",
                id: "5732094512726016",
                screenshot1_small: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5732094512726016&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "The infamous dentist game is back",
                icon_small: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>The infamous dentist game is back! Play as the dentist to famous pop stars! Repair broken, decayed and damaged teeth, by using a variety of utensils. Watch as the famous stars start twitching, blinking and turning red.</p> <p>Cute, and guaranteed fun!</p> <p>Features:</p> <ul> <li>5 different pop stars to play with (Justin, Drake, Selena and more)</li> <li>9 different dental tools</li> <li>multiple types of teeth to repair</li> <li>able to punch or kiss the pop stars</li> <li>fun animations, suitable for all ages</li> <li>various decorations</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/pop-star-dentist2/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Sports",
                screenshot2_small: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 14,
                language: "en",
                title: "9 Ball Pool",
                date_added: "12-01-2017",
                id: "5635222599106560",
                screenshot1_small: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5635222599106560&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "How fast can you pot the 9 ball?",
                icon_small: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Love playing pool tables? How fast can you pot the 9 ball?</p> <p> Features: </p> <ul> <li>Realistic physics</li> <li>Intuitive aiming and shooting system</li> <li>Fun, pool-like atmosphere</li> <li>Tutorial to learn the ropes</li> </ul> ",
                screenshot3_small: "https://cdn.marketjs.net/games/9-ball-pool/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action",
                screenshot2_small: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 28,
                language: "en",
                title: "Zone 90",
                date_added: "12-01-2017",
                id: "6280447701024768",
                screenshot1_small: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6280447701024768&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Build your army and conquer",
                icon_small: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>The year is 2100. Nations have ceased to exist, replaced by rogue corporations bent on extracting every last natural resource on Earth. What was once diplomatic business turned into violent confrontations between these rogue entities.</p> <p>Zone 90 is last, untouched region, rich with natural resources. It's now tightly contested between two corporations: XetraCorp and BT Industries. Whoever controls Zone 90, dictates the fate of the world.</p> <p>Play as either faction. Build your base, train an army and battle! Drive the enemy out of Zone 90, and rule the world!</p> <p>Features:</p> <ul> <li>Two game modes: Skirmish and Mission Modes</li> <li>Breathtaking graphics</li> <li>Riflemen, rockeeteers, Humvees, Tanks and Defense Turrets : what more do you need?</li> <li>Clever enemy AI: can you beat it?</li> <li>Cross-platform RTS experience (experience the same action on desktop and mobile)</li> <li>Multi-unit selection</li> <li>Innovative waypoint system</li> <li>Building and unit management system</li> <li>Scrolling system</li> <li>Minimap for combat response</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/zone-90/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Sports",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 50,
                language: "en",
                title: "Social Blackjack",
                date_added: "02-03-2017",
                id: "6253902005534720",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6253902005534720&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Play Blackjack with friends",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Blackjack is a game best played with friends.</p> <p>Play in a social setting, with other players. Can you beat the house?</p> <p>Features:</p> <ul> <li>Fun and sleek theme, suitable for card game enthusiasts</li> <li>Casual play mode where users can drop in and out of the game</li> <li>Tournament mode (player vs player)</li> <li>Chat and play with other players in real time</li> <li>Choose fun avatars to represent yourself</li> <li>Custom nicknames</li> <li>Really easy and intuitive controls, for desktop and mobile (smartphones and tablets). </li> <li>Emoji support in nicknames. Use https://getemoji.com and paste into nickname field.</li> <li>Leaderboards for competitive play</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/social-blackjack/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 51,
                language: "en",
                title: "Clash of Vikings",
                date_added: "02-02-2017",
                id: "5114963651723264",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "true",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5114963651723264&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Lead your army of vikings to victory",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>The battlefield is set. It's you versus the other viking kingdom.</p> <p>You have 3 minutes to defeat your enemy. Choose the right battle cards and place your heroes on the battlefield.</p> <p>Defeat the enemy kingdom to win the game!</p> <p>Use different combinations of card decks and strategies to defeat the enemy.</p> <p>Features:</p> <ul> <li>Different cards to choose from, including troops, heroes and spells.</li> <li>Use your management skills to pick the right cards against the enemy.</li> <li>Arrange your card deck before each battle</li> <li>Interactive tutorial to learn the basics. The advanced tactics and strategies are you to master.</li> <li>Very clever enemy AI. Be warned!</li> <li>Fun and upbeat viking theme</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/clash-of-vikings/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family,Action",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 21,
                language: "en",
                title: "Pet Hop",
                date_added: "02-01-2017",
                id: "5652005288673280",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "true",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5652005288673280&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Hop your way past busy traffic",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Rabbit is out on the loose! Hop your way to cross the busy traffic. Don't get squashed!</p> <p>Features:</p> <ul> <li>Easy and intuitive controls. Tap to move forward, swipe left or ride to move horizontally</li> <li>Collect coins to unlock various pets in the shop</li> <li>Play characters such as panda, tiger and chicken</li> <li>Dynamic generation of terrain to provide endless gameplay</li> <li>If you've played crossy type games, this is a perfect fit.</li> <li>Fun 3D-like theme</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/pet-hop/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 34,
                language: "en",
                title: "Hostage Rescue",
                date_added: "10-24-2016",
                id: "5677428542275584",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5677428542275584&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Rescue hostages, defeat the bad guys.",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>In this classic first person shooter, you're an agent tasked with rescuing hostages. Use your fast reflexes and wits to defeat the bad guys.</p> <p>Don't forget to reload when your gun is empty!</p> <p>Features:</p> <ul> <li>interactive tutorial to learn the ropes</li> <li>fast, crisp action first person shooter</li> <li>fight your way through all kinds of enemies and thugs</li> <li>gunfights in 5 different locations</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/hostage-rescue/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family,Sports",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 18,
                language: "en",
                title: "Donut Slam Dunk",
                date_added: "10-19-2016",
                id: "5408968994193408",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5408968994193408&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Place the donut into the box",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>The donut is swinging gently from a rope. To score a donut slam dunk, time the donut's release to make it fall nicely into the box.</p> <p>How many donut slam dunks can you make?</p> <p>Features:</p> <ul> <li>A fun theme, perfect for outdoor</li> <li>Unlimited levels for unlimited gameplay</li> <li>Bonus points for factors such as speed, ricochets, and accuracy</li> <li>A variety of obstacles such as bouncers and spikes, to make things challenging</li> <li>Stuck? Earn coins to purchase magnets and springs to help</li> <li>Interactive tutorial to learn the ropes</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/donut-slam-dunk/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family,Action,Puzzle",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 39,
                language: "en",
                title: "Grenade Toss",
                date_added: "09-27-2016",
                id: "5690952052113408",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "true",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5690952052113408&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Aim and throw grenades to defeat the enemy",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Throw grenades at the enemy to defeat them. Control the angle and strength of your throws.</p> <p>Remember to watch your grenade count! You have a limited amount per level.</p> <p>Features:</p> <ul> <li>A variety of obstacles including challenging terrain, and objects such as boxes, pulleys and TNTs.</li> <li>Simple point and click throwing mechanic</li> <li>Interactive tutorial</li> <li>30 challenging levels</li> <li>Fun theme and music</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/grenade-toss/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Puzzle,Family",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 23,
                language: "en",
                title: "Claw Crane",
                date_added: "09-12-2016",
                id: "6262525024796672",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6262525024796672&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Control the claw crane to pick up aliens",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Cute, cuddly aliens find themselves on lost in space. Use the claw crane to pick them up and transport them to safety.</p> <p>Features:</p> <ul> <li>Use a variety of powerups to improve your pick-ratio. From freeze, to combo points, to extra time, there's a whole lot to claw on!</li> <li>Unlimited levels</li> <li>Fun space theme</li> <li>Interactive tutorial to learn the ropes</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/alien-claw-crane/localization/en/media/graphics/promo/screenshots/3.jpg"
                }
 
]