export const LEADERBOARDGAMES:any = [
                {
                genres: "Action,Sports",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 12,
                language: "en",
                title: "Tank Battle",
                date_added: "12-05-2015",
                id: "5764813410009088",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5764813410009088&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Outsmart the enemy tank",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Two tanks emerge on the battlefield. Only one will survive. Can you outsmart the other tank?</p> <p>Collect ammo crates and powerups. Navigate your way to the enemy tank. Fire away!</p> <p>This is the perfect game to play with friends and family.</p> <p>Tip: For two player mode, play on the same device (one finger on each side). Enhance social interaction of your audience!</p> <p>Features:</p> <ul> <li>Interactive tutorial to learn the ropes</li> <li>Collect different powerups such as additional health, bubble shields and speed boost</li> <li>Randomly generated battlefield. Each terrain is different</li> <li>Intelligent computer AI</li> <li>Singleplayer or Two Player mode</li> <li>Beautiful, low polygon theme</li> <li>Unlimited gameplay</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/tank-battle/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 14,
                language: "en",
                title: "Millionaire Quiz",
                date_added: "12-04-2015",
                id: "5666530331197440",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5666530331197440&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Enter the game show, win a million dollars",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>How good is your trivia knowledge? Put your skills to test against the ultimate game show, Millionaire Quiz!</p> <p>Answer trivia questions ranging from Science, Technology, Sports, Music and Health.</p> <p>Features:</p> <ul> <li>Fun game show theme. Live the glitz and glamor of a contestant</li> <li>Entertaining game show host</li> <li>Stuck? Use the 3 lifelines ( call a friend, eliminate other answers, and ask the audience)</li> <li>Challenging questions. They only get tougher the farther you get</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/millionaire-quiz/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Puzzle,Family",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 21,
                language: "en",
                title: "Bounce Prediction",
                date_added: "12-03-2015",
                id: "5093293931102208",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5093293931102208&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Predict where the ball will bounce",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Can you predict where the ball will bounce next? Study the puzzle set carefully, analyze the possible angles before placing your prediction.</p> <p>A fun and challenging game to stimulate cognitive ability.</p> <p>Features:</p> <ul> <li>Random puzzle sets</li> <li>15 sets per round</li> <li>Increasingly difficult puzzle sets</li> <li>Daily metrics to track your performance. Play daily to boost your cognitive ability</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action,Family",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 40,
                language: "en",
                title: "Banana Jungle",
                date_added: "11-30-2015",
                id: "5638327160012800",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5638327160012800&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Collect bananas, avoid obstacles",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Play as a gorilla in a beautiful jungle. Collect bananas, and avoid obstacles such as thorny mushrooms, boulders and tree logs. How far can you go?</p> <p>Features:</p> <ul> <li>Simple one-touch gameplay. Pick up your device and start playing!</li> <li>Clear tutorial provided.</li> <li>Stunning graphics</li> <li>Fun theme</li> <li>Great music</li> <li>Increasingly difficult challenges. Every round is different. Easy to learn, hard to master.</li> <li>Hours of addictive gameplay</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/banana-jungle/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family,Puzzle",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 21,
                language: "en",
                title: "Pack The Bag",
                date_added: "11-25-2015",
                id: "5643938803220480",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5643938803220480&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Use your spatial skills to pack the bag ",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>How good are you at organizing things in confined spaces? Play Pack the Bag, a fun game to train your spatial skills.</p> <p>Improve your spatial skills by placing the item correctly in the bag. Track your daily performance, and compare it with previous days.</p> <p>Features:</p> <ul> <li>crisp and fast animations</li> <li>increasingly difficult challenges</li> <li>a tutorial system</li> <li>a beautiful daily/weekly chart to analyze your performance</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Match 3,Family",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 12,
                language: "en",
                title: "Connect The Dots",
                date_added: "11-09-2015",
                id: "5649862905298944",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5649862905298944&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Connect dots of the same color",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Connect dots of the same color. Meet the minimum dots required for each level. Beware, don't run out of moves!</p> <p>Features:</p> <ul> <li>Over 36 really challenging levels</li> <li>Learn new abilities along the way</li> <li>Encounter increasingly tricky puzzle sets</li> <li>Fun theme suitable for all ages</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/connect-the-dots/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action,Family",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 161,
                language: "en",
                title: "Count Pero Toaster Jump",
                date_added: "11-05-2015",
                id: "5089055335251968",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5089055335251968&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Grab food launched from the toaster",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Count Pero is a cute vampire zombie, and he's very hungry. Launch him out of a toaster, and collect the delicious food along the way. Try to avoid falling flat on the kitchen table!</p> <p>Features</p> <ul> <li>Endless gameplay</li> <li>Collect different kinds of food - pizza, veggies, meat and more</li> <li>3D like graphics</li> <li>Fun theme suitable for family and young kids</li> </ul> ",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/mad-box-zombies-toaster/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 24,
                language: "en",
                title: "My Pet Spa",
                date_added: "11-05-2015",
                id: "5742053036130304",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5742053036130304&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Take care of pets in your spa",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Play as a pet spa owner. Our pet needs attention and love from you. Get hands on, as you brush, clean, blow-dry, cut the nails, and dress up the pet. A lot of fun guaranteed for kids, girls and the entire family.</p> <p>Features:</p> <ul> <li>4 cute animals (kitten, dog, baby bear and baby lion)</li> <li>5 different pet grooming techniques</li> <li>A large wardrobe : dress up your pet with the cutest clothing and accessories</li> <li>Take a picture function</li> <li>Save your creations to the gallery</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/petspa/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "",
                screenshot2_small: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 39,
                language: "en",
                title: "Street Racing Mania",
                date_added: "08-27-2015",
                id: "5713912150360064",
                screenshot1_small: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "true",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5713912150360064&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "The ultimate street racing game",
                icon_small: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Do you like racing games? Street Racing Mania chronicles the every day life of a street racer. Buy upgrades, race the streets, earn money and buy better cars!<p> <p>Beware though, each race is extremely challenging. Make it towards the finish line to earn your paycheck!</p> <p>Features:</p> <ul> <li>5 different tracks</li> <li>Day and night racing</li> <li>Police cars!</li> <li>Pedestrians! Avoid, or not avoid them.</li> <li>Challenging AI</li> <li>A shop for upgrading</li> <li>Pumping music</li> <li>Simple tap mechanism for vehicle control</li> </ul>",
                screenshot3_small: "https://whitelabel-cdn.marketjs.com/games/street-racing-mania/localization/en/media/graphics/promo/screenshots/3.jpg"
                }
]