export const MULTIPLAYERGAMES = [
        {
        plays: 8,
        language: "en",
        title: "Poker with Buddies",
        date_added: "03-12-2021",
        id: "4947100933554176",
        icon_large: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4947100933554176&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Texas hold em poker with friends",
        icon_small: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Play Texas Hold 'Em poker with anyone on the internet. Place virtual chips on the table, and try to outsmart the other players and the dealer. Meet new friends online over casual poker games. Want to only play with your friends? No problem. Set up a private room with a password. Features: - Up to 6 players in a room - Unlimited rooms - Chat functionality - Play if bots or AI, if humans are not present - Automatic room assignment - Private rooms with password is now possible - Pick a cool avatar before joining the room Fans of Texas Holdem Poker will appreciate this game."
        },
        {
        plays: 1,
        language: "en",
        title: "Fishing With Buddies",
        date_added: "03-12-2021",
        id: "5097370699169792",
        icon_large: "http://subscription-cdn.marketjs.com/games/fishing-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/fishing-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5097370699169792&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/fishing-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/fishing-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Catch fish together with your friends!",
        icon_small: "http://subscription-cdn.marketjs.com/games/fishing-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/fishing-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A real-time multiplayer game where you go deep water fishing with your friends. Take aim and fire your harpoon to catch the fish. Unlock special powerups such as Rapid Fire, Exploding Net, and Ocean Vortex. Who will emerge the winner at the end of this multiplayer fishing game? Features: - Extremely simple controls - 2 minute gameplay, perfect for casual rounds - 4 players in a room - Unlimited rooms - Customize your nickname and avatar - Score combos and unlock special powerups. Open the ocean vortex to catch additional fish."
        },
        {
        plays: 14,
        language: "en",
        title: "Archery with Buddies",
        date_added: "03-12-2021",
        id: "5779332266983424",
        icon_large: "http://subscription-cdn.marketjs.com/games/archery-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/archery-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5779332266983424&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/archery-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/archery-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Shoot arrows with your friends",
        icon_small: "http://subscription-cdn.marketjs.com/games/archery-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/archery-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Flick to shoot arrows at the archery board in this multiplayer PvP game. Time and adjust your archer shots to land a bullseye to score extra points. Can you be king or queen of archery? Master the game and become the bowmaster. Features: - Split screen feature. Train to be an archer king or queen. - Play in real time against your friends - Constantly moving archery board - Taunt your friends with emojis"
        },
        {
        plays: 5,
        language: "en",
        title: "Sumo Push Push",
        date_added: "03-12-2021",
        id: "5386651997044736",
        icon_large: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5386651997044736&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Attack and defend lanes with Sumo warriors",
        icon_small: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/sumo-push-push/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap on the dirt lanes, to launch your Sumo heroes forward. Overpower your opponents with clever placement of Sumo warriors. Make use of different Sumo weight classes to win lane control, in this fast paced multiplayer PvP game. Features: - Exciting Player vs Player (PvP) game mechanic - Sumo theme with Sumo warriors and hero theme - Random selection of opponents in this multiplayer game - Play with your friends in real-time - Taunt your friends using emoticons - Chat with your friends while playing"
        },
        {
        plays: 0,
        language: "en",
        title: "Math Trivia LIVE",
        date_added: "03-12-2021",
        id: "5660320652591104",
        icon_large: "http://subscription-cdn.marketjs.com/games/math-trivia-live/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/math-trivia-live/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5660320652591104&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/math-trivia-live/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/math-trivia-live/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Multiplayer quiz with friends",
        icon_small: "http://subscription-cdn.marketjs.com/games/math-trivia-live/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/math-trivia-live/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "How fast can you calculate math in your head? Hurry up, because your opponent is doing the same! In this rapid-fire math quiz, the player who scores the most after 10 rounds wins! Play against anyone around the world on their smartphone, tablet device or computer. Features: - Randomly generated questions - 10 questions per round - Fun trivia theme and environment - Avatar selection - Play against humans or practice against bots"
        },
        {
        plays: 1,
        language: "en",
        title: "Golden Goal with Buddies",
        date_added: "03-12-2021",
        id: "5973751393943552",
        icon_large: "http://subscription-cdn.marketjs.com/games/golden-goal-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/golden-goal-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5973751393943552&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/golden-goal-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/golden-goal-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Take penalty kicks against your friends",
        icon_small: "http://subscription-cdn.marketjs.com/games/golden-goal-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/golden-goal-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Play against random opponents and friends in this live multiplayer soccer game. Swipe upwards to kick. Can you beat your opponent's score? Features: - Split screen feature. Compete in real time against your friends - Challenging goalkeeper to beat - Upbeat sports theme"
        },
        {
        plays: 3,
        language: "en",
        title: "Snakes and Ladders",
        date_added: "03-12-2021",
        id: "6320790204055552",
        icon_large: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6320790204055552&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Roll the dice to win. Play with your friends online!",
        icon_small: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/snakes-and-ladders/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Your life is represented by ladders (opportunities) and snakes (challenges). Roll the dice to navigate your pieces across the board in this fun multiplayer game. Arrive at a ladder, and advance faster. Arrive at a snake, and be transferred back a few steps. Who will win in this game of chance? Features: - Play with 2 or 4 people in a room. - Chat and make friends in this multiplayer casual game. - Easy to pick up and play. Anybody can win! - Plenty of avatars to choose from. - No friends? Play with the computer - Custom username. - Responsive and Full screen mode available."
        },
        {
        plays: 10,
        language: "en",
        title: "Carrom with Buddies",
        date_added: "03-12-2021",
        id: "5345886365286400",
        icon_large: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5345886365286400&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Play carrom with your friends online",
        icon_small: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/carrom-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Revive your childhood dreams by playing Carrom with your buddies. Cover the Queen (Pot the Queen, followed by a Carrommen). Pot all your Karrom pieces with the Queen, covered before the last Carom piece. Features: - Beautiful board and Karom pieces - 2 player mode - Play with either a human or a bot - Private mode where you can play with a designated password - Realistic physics - Elegantly designed notifications - Clean and modern design - Emojis to express yourself"
        }
]