export const POPULARGAMES = [
                {
                genres: "Action,Family",
                screenshot2_small: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 5,
                language: "en",
                title: "Giant Hamster Run",
                date_added: "12-01-2017",
                id: "5728759688724480",
                screenshot1_small: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5728759688724480&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "A giant hamster has escaped",
                icon_small: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>You're a tiny hamster turned into a giant hamster. Suddenly, everything seems so small. Run along the city streets.</p> <p>Switch lanes, jump and slide to avoid obstacles such as roadblocks and police cars. Collect coins and cookies along the way. Use coins to purchase cool items, such as a skateboard, rocket pack and yes, a magic carpet!</p> <p>How far can you run?</p> <p>Features:</p> <ul> <li>Interactive tutorial</li> <li>Revolutionary first person 3D-like view</li> <li>Fun theme and music</li> <li>Easy and intuitive controls</li> <li>Extremely cute hamster</li> <li>Endless gameplay</li> <li>A shop with items to unlock</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/giant-hamster-run/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action,Family,Adventure",
                screenshot2_small: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 5,
                language: "en",
                title: "Temple Crossing",
                date_added: "12-01-2017",
                id: "5162027211292672",
                screenshot1_small: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5162027211292672&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Explore the temple, avoid the fall",
                icon_small: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Guide the explorer into the temples. Build the bridge, and help him cross safely to the other side. Use your timing to build the perfect bridge. How many bridges can you cross?</p> <p></p> <p> Features: </p> <ul> <li>Tutorial to learn the ropes</li> <li>Tons of coins to collect</li> <li>Use coins to purchase powerups</li> <li>Powerups such as jump, second life and accurate eye</li> <li>A fun and relaxing theme</li> </ul> ",
                screenshot3_small: "https://cdn.marketjs.net/games/temple-crossing/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Sports",
                screenshot2_small: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 10,
                language: "en",
                title: "Guess The Soccer Star",
                date_added: "12-01-2017",
                id: "5636317496999936",
                screenshot1_small: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5636317496999936&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "How well do you know the soccer stars?",
                icon_small: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>How well do you know the soccer stars of the world? Test your knowledge of the soccer universe.</p> <p>Features:</p> <ul> <li>Extremely easy learning curve. Simply guess the last name!</li> <li>Earn coins for every puzzle solved</li> <li>Stuck? Use your coins, to activate a variety of helper tools to solve the puzzle. Use tools such as - Reveal and Remove Letter to guess.</li> <li>Fun theme and music</li> <li>Over 99 soccer celebrities</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/guess-the-soccer-star/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family,Puzzle",
                screenshot2_small: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 8,
                language: "en",
                title: "Baby Chick Maze",
                date_added: "12-01-2017",
                id: "5753795321528320",
                screenshot1_small: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5753795321528320&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Guide the baby chick around the farm",
                icon_small: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Poor baby chick is lost in the farm. Using your finger, create a trail and guide her to mother chicken. Avoid obstacles like walls, haystacks and trees. Be careful of wandering foxes!</p> <p>Features:</p> <ul> <li>Innovative tracing mechanic (trace anywhere along the screen to move the baby chick)</li> <li>A story line suitable for kids of young ages</li> <li>Unlimited retries</li> <li>Happy theme and music</li> <li>Bright design suitable for family, teens and kids</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/baby-chick-maze/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action,Family",
                screenshot2_small: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 30,
                language: "en",
                title: "Kitten Bounce",
                date_added: "12-01-2017",
                id: "5757790714855424",
                screenshot1_small: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5757790714855424&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Bounce kitten towards the milk",
                icon_small: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Kitten needs milk! Navigate your way from cannon to cannon, collecting balls of yarn along the way. Tap on the cannon to blast the kitten towards the end zone! Guaranteed fun for audience of all ages.</p> <p>Aim correctly, and blast the kitten! Carefully hand-eye coordination required</p> <p>Features:<p> <ul> <li>over 20 carefully designed levels, with hours of gameplay. Puzzles get more difficult over time</li> <li>cute kitten theme</li> <li>cute effects and music</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/kitten-bounce/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action",
                screenshot2_small: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 37,
                language: "en",
                title: "Slots Beach",
                date_added: "12-01-2017",
                id: "5724977164713984",
                screenshot1_small: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5724977164713984&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Play the slot machine",
                icon_small: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Like to play slot machines? Let Lola teach you how to play. Match 3 fruits, in over 17 winning combinations to win more coins. A fun slots game for everyone.</p> <p>Features:</p> <ul> <li>Beautifully designed slot machine interface: bright, colorful and intuitive</li> <li>Beautiful beach theme and fruits to match</li> <li>Lucky bonus: get a chance to spin the wheel of fortune</li> <li>Hourly bonus: come back for more free coins!</li> <li>A tutorial system</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/slots-beach/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Puzzle,Family",
                screenshot2_small: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 6,
                language: "en",
                title: "Spades",
                date_added: "12-01-2017",
                id: "5769014806577152",
                screenshot1_small: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5769014806577152&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Classic spades card game",
                icon_small: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "Play classic 4 player spades. Team up with an AI, make your bids and attempt to win the game. Spades is a fun card game involving strategy, probability and taking chances. Features - Blind nil function - Tutorial to explain the rules of the game - Bonus round for score ties - Casual relaxed environment for playing - Play against competent AI bots",
                screenshot3_small: "https://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family,Puzzle",
                screenshot2_small: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 7,
                language: "en",
                title: "Chicken & Cake",
                date_added: "12-01-2017",
                id: "5677242361315328",
                screenshot1_small: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5677242361315328&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Help Mr. Chicken solve math problems",
                icon_small: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "Help Mr. Chicken solve subtraction problems. Teach your kids how to subtract numbers. Suitable for kids 4- 12 Features: - 3 difficulty levels - cute characters for kids - cute theme revolving cakes",
                screenshot3_small: "https://cdn.marketjs.net/games/chickencake/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Puzzle,Family",
                screenshot2_small: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 6,
                language: "en",
                title: "Word Finder",
                date_added: "12-01-2017",
                id: "5761676318081024",
                screenshot1_small: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5761676318081024&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "How quickly can you spot the words?",
                icon_small: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>If you think you're good at word games, think again. How quickly can you spot the words?</p> <p>How to play: Click and drag the words to highlight them. It's that simple!</p> <p>Features:</p> <ul> <li>Fun theme, suitable for all ages and situations</li> <li>3 different levels of difficulty (Easy, Medium and Hard)</li> <li>Expand your vocabulary. Learn words from different domains, including the Internet, Painters, Foreign Languages, Artists, Composers, Animals, Countries and more.</li> <li>Extremely high replayability</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/word-finder/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Puzzle,Family",
                screenshot2_small: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 7,
                language: "en",
                title: "Baby Cow Launcher",
                date_added: "12-01-2017",
                id: "6315703745380352",
                screenshot1_small: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6315703745380352&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Stop the greedy farmers. Launch baby cows!",
                icon_small: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>The greedy farmers are milking cows for profit. As General Cow, your task is to disrupt these greedy farmers.</p> <p>Launch baby cows at greedy farmers to defeat them. Use a variety of power ups to win!</p> <p>Features:</p> <ul> <li>Baby cows with unique abilities</li> <li>Over 20 challenging levels</li> <li>Very cool physics terrain</li> <li>Challenging objects such as crates, glass, windmill, and more.</li> <li>Beautiful farm scenery</li> <li>Relaxing theme, suitable for an afternoon sit-down game session</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/screenshots/3.jpg"
                }
]