export const PUZZLEGAMES:any =[
        {
        plays: 29,
        language: "en",
        title: "Stupid Zombies 2",
        date_added: "03-12-2021",
        id: "4806726235717632",
        icon_large: "http://subscription-cdn.marketjs.com/games/stupid-zombies-2/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/stupid-zombies-2/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4806726235717632&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/stupid-zombies-2/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/stupid-zombies-2/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Sequel hit zombie game with over 50 million downloads",
        icon_small: "http://subscription-cdn.marketjs.com/games/stupid-zombies-2/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/stupid-zombies-2/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "The undead return in this new, jam-packed release of Stupid Zombies 2. Select your character, and unleash your bullets at brainless zombies. They say you can’t kill what is already dead, but it can't hurt to do more damage. Features: - Multiple levels with multiple chapters - Innovative ricochet based gameplay. Defeat the stupid zombies with brains and ingenuity. - Realistic physics - Zombie halloween theme"
        },
        {
        plays: 18,
        language: "en",
        title: "Monster World",
        date_added: "07-17-2018",
        id: "5383533419823104",
        icon_large: "http://cdn.marketjs.net/games/monster-world/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/monster-world/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5383533419823104&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/monster-world/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/monster-world/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Remove blocks to reach the monster",
        icon_small: "http://cdn.marketjs.net/games/monster-world/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/monster-world/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Move the main character, Ozzy to the giant monster at the bottom. Remove other blocks by tapping on them. Beware, it gets slippery!</p> <p>Features:</p> <ul> <li>over 20 levels</li> <li>increasing challenging levels that require you to think</li> <li>entertaining music</li> </ul>"
        },
        {
        plays: 21,
        language: "en",
        title: "Bounce Prediction",
        date_added: "12-03-2015",
        id: "5093293931102208",
        icon_large: "http://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5093293931102208&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Predict where the ball will bounce",
        icon_small: "http://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://whitelabel-cdn.marketjs.com/games/bounce-prediction/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Can you predict where the ball will bounce next? Study the puzzle set carefully, analyze the possible angles before placing your prediction.</p> <p>A fun and challenging game to stimulate cognitive ability.</p> <p>Features:</p> <ul> <li>Random puzzle sets</li> <li>15 sets per round</li> <li>Increasingly difficult puzzle sets</li> <li>Daily metrics to track your performance. Play daily to boost your cognitive ability</li> </ul>"
        },
        {
        plays: 18,
        language: "en",
        title: "Candy Slide",
        date_added: "12-01-2017",
        id: "6561387149000704",
        icon_large: "http://cdn.marketjs.net/games/candy-slide/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/candy-slide/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6561387149000704&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/candy-slide/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/candy-slide/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Slide the candy to freedom",
        icon_small: "http://cdn.marketjs.net/games/candy-slide/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/candy-slide/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Drag or swipe the blue candy blocks. Clear a path for the red candy block. In how many moves can you complete the puzzle?</p> <p>Features:</p> <ul> <li>Delicious candy theme</li> <li>24 challenging levels</li> <li>Stuck? Use the interactive hints system</li> </ul>"
        },
        {
        plays: 7,
        language: "en",
        title: "Crazy Truck Parking",
        date_added: "03-12-2021",
        id: "4836064888881152",
        icon_large: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4836064888881152&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Attempt to park your truck, with precision.",
        icon_small: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Truck parking simulator game. It's easy to learn, and yet incredibly difficult to master. Park your truck in the perfect spot, with surgical precision. Be careful not to bump into other trucks and obstacles. Fasten your safety belt, and let the game begin! Fans of parking frenzy games will love this. Features: - Interactive tutorial - Beautiful parking spots - 3 Star based system to reward precision - Over 50+ parking challenges - Keyboard controls for desktop, and touch controls for smartphones and tablets - Drive a variety of cool cars"
        },
        {
        plays: 41,
        language: "en",
        title: "Teddy Bubble Rescue",
        date_added: "04-28-2020",
        id: "6528039954415616",
        icon_large: "http://subscription-cdn.marketjs.com/games/teddy-bubble-rescue/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/teddy-bubble-rescue/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6528039954415616&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/teddy-bubble-rescue/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/teddy-bubble-rescue/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Shoot bubbles to rescue mini teddy bears",
        icon_small: "http://subscription-cdn.marketjs.com/games/teddy-bubble-rescue/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/teddy-bubble-rescue/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Big Teddy needs your help! Pop the bubbles to rescue the mini teddy bears. Place your bubble shooter aim carefully to clear the maximum amount of bubbles in each level. Features: - Interactive tutorial - 20 challenging levels - Fun theme - Solve bubble sets using a variety of tactics. Use clever theory of angles, target higher bubbles and other tactics to solve each level"
        },
        {
        plays: 8,
        language: "en",
        title: "London Jigsaw Puzzle",
        date_added: "03-12-2021",
        id: "4827298726412288",
        icon_large: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4827298726412288&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Discover London via jigsaw puzzles",
        icon_small: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/london-jigsaw-puzzle/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Arrange the jigsaw pieces of famous landmarks in London. Solve puzzles of famous sights such as the London Eye, Big Ben, Tower of London, Buckingham Palace, Hyde Park, Trafalgar Square, Westminster Abbey and more. Features: - Modern instagram type design, suitable for a young and millennial audience. - Hints system. - Zoom function to zoom out. - Modify the number of pieces each row or column. - Select different backgrounds to work on. - Peaceful theme and music."
        },
        {
        plays: 8,
        language: "en",
        title: "OMG Word Pop",
        date_added: "06-21-2019",
        id: "6272975256944640",
        icon_large: "http://cdn.marketjs.net/games/omg-word-pop/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/omg-word-pop/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6272975256944640&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/omg-word-pop/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/omg-word-pop/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Tap and drag to form words",
        icon_small: "http://cdn.marketjs.net/games/omg-word-pop/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/omg-word-pop/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap and drag to form words. How good is your vocabulary? Is the word too difficult? Earn a better score to unlock hints. Features: - Intuitive swipe mechanic to form English words. - Interactive tutorial. - Challenging levels. Start with one word, then two, and more. Words get more complicated as you progress. - Hints system."
        },
        {
        plays: 9,
        language: "en",
        title: "Hidden Objects Pirate Adventures",
        date_added: "07-17-2018",
        id: "4886580755955712",
        icon_large: "http://cdn.marketjs.net/games/hidden-objects-pirate-adventures/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/hidden-objects-pirate-adventures/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4886580755955712&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/hidden-objects-pirate-adventures/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/hidden-objects-pirate-adventures/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Help the pirate king recover his lost treasures",
        icon_small: "http://cdn.marketjs.net/games/hidden-objects-pirate-adventures/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/hidden-objects-pirate-adventures/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Once upon a time, there was a pirate who had all the treasures in the world. During a war, he lost all his treasure and fame. Now, he's on a journey to reclaim his lost treasures. Help him restore glory!</p> <p>This is a classic hidden object game, where the player spots treasures in a fun, pirate setting.</p. <p>Features:</p> <ul> <li>a fun storyline to induce excitement</li> <li>over 60 items to discover throughout the course of your adventure</li> <li>three different settings, following the storyline</li> <li>a simple tutorial system to get started</li> <li>high scores to compare performance</li> </ul>"
        },
        {
        plays: 10,
        language: "en",
        title: "School Bus Pickup",
        date_added: "07-17-2018",
        id: "5683615469928448",
        icon_large: "http://cdn.marketjs.net/games/school-bus-pickup/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/school-bus-pickup/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5683615469928448&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/school-bus-pickup/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/school-bus-pickup/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Plan your school bus routes",
        icon_small: "http://cdn.marketjs.net/games/school-bus-pickup/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/school-bus-pickup/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>School season is back. Play as a school bus driver. Plan your bus routes correctly, drop off kids at the correct schools.</p> <p>Features:</p> <ul> <li>Challenging puzzles</li> <li>Easy learning curve. Simply drag to plan the bus routes</li> <li>6 different towns (Lunar Valley, Beverly Hills, Plucky Palms and more)</li> <li>Stuck? Use the hints option</li> <li>5 different characters</li> <li>5 different busses to plan around</li> </ul>"
        },
        {
        plays: 8,
        language: "en",
        title: "Unblock It HD",
        date_added: "03-12-2021",
        id: "4893044626161664",
        icon_large: "http://subscription-cdn.marketjs.com/games/unblock-it-hd/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/unblock-it-hd/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4893044626161664&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/unblock-it-hd/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/unblock-it-hd/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Slide the wooden blocks to victory",
        icon_small: "http://subscription-cdn.marketjs.com/games/unblock-it-hd/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/unblock-it-hd/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Drag or swipe the wooden blocks. Clear a path for the blue colored block. How many moves do you need, to complete the game? Features: - Zen, wooden block theme - 24 challenging levels - Interactive hint system to help solve the puzzle"
        },
        {
        plays: 39,
        language: "en",
        title: "Stickman Swing",
        date_added: "09-16-2019",
        id: "5753039202811904",
        icon_large: "http://cdn.marketjs.net/games/stickman-swing/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/stickman-swing/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5753039202811904&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/stickman-swing/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/stickman-swing/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Swing and hook like a spider",
        icon_small: "http://cdn.marketjs.net/games/stickman-swing/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/stickman-swing/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: " Tap to hook. Swing and make incredible jumps. Execute crazy acrobatic tricks like a stickman boss. Avoid obstacles at all costs. Features: - Simple controls and fun gameplay. - Unlimited levels! Play forever. - Swing like spider man stick edition. - Funky urban theme. - Grappling hooks and bouncers included."
        },
        {
        plays: 9,
        language: "en",
        title: "Pattern Flex",
        date_added: "12-01-2017",
        id: "5129511356071936",
        icon_large: "http://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5129511356071936&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Can you remember the patterns?",
        icon_small: "http://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>How good is your memory? Play Pattern Flex, a fun memory game for the family.</p> <p>Improve your memory with multiple shapes. Track your daily performance, and compare it with previous days.</p> <p>Features:</p> <ul> <li>crisp and fast animations</li> <li>a tutorial system</li> <li>a beautiful daily/weekly chart to analyze your performance</li> </ul>"
        },
        {
        plays: 1,
        language: "en",
        title: "Jewels Blocks Puzzle",
        date_added: "03-12-2021",
        id: "5658800905256960",
        icon_large: "http://subscription-cdn.marketjs.com/games/jewels-blocks-puzzle/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/jewels-blocks-puzzle/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5658800905256960&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/jewels-blocks-puzzle/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/jewels-blocks-puzzle/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Create rows of jewels to win",
        icon_small: "http://subscription-cdn.marketjs.com/games/jewels-blocks-puzzle/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/jewels-blocks-puzzle/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Drag and drop jewel blocks to fill the empty gap. Complete a row of beautiful jewels to score points. Complete 2 rows or more to score bonus points. How high can you score? Features: - Interactive tutorial - Endless gameplay. Play until you run out of turns. - Mesmerizing jewel theme to encourage focus and productivity. - Fans of tetris and trixology will love this."
        },
        {
        plays: 9,
        language: "en",
        title: "Slice of Zen",
        date_added: "07-17-2018",
        id: "5081328515022848",
        icon_large: "http://cdn.marketjs.net/games/slice-of-zen/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/slice-of-zen/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5081328515022848&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/slice-of-zen/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/slice-of-zen/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How well can you slice?",
        icon_small: "http://cdn.marketjs.net/games/slice-of-zen/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/slice-of-zen/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Slice away as much of the object as possible. Hit the target to win the level.</p> <p>Features:</p> <ul> <li>Different objects to slice away</li> <li>Zen theme, great for focus and relaxation</li> <li>Over 20 challenging levels</li> </ul>"
        },
        {
        plays: 6,
        language: "en",
        title: "One Liner",
        date_added: "06-21-2019",
        id: "5115738496958464",
        icon_large: "http://cdn.marketjs.net/games/one-liner/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/one-liner/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5115738496958464&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/one-liner/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/one-liner/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Draw one line without lifting a finger",
        icon_small: "http://cdn.marketjs.net/games/one-liner/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/one-liner/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Draw one single line, without ever lifting your finger or mouse. How many levels can you complete? Deceptively simple, yet profoundly deep game. Features: - Interactive tutorial - Over 120 challenging levels to keep you occupied - Upbeat, rhythmic theme - How difficult can this be? Just Draw 1 Line!"
        },
        {
        plays: 59,
        language: "en",
        title: "Didi And Friends Guess What",
        date_added: "09-16-2019",
        id: "4795799440457728",
        icon_large: "http://cdn.marketjs.net/games/didi-and-friends-guess-what/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/didi-and-friends-guess-what/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4795799440457728&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/didi-and-friends-guess-what/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/didi-and-friends-guess-what/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Guess the character behind the shadow",
        icon_small: "http://cdn.marketjs.net/games/didi-and-friends-guess-what/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/didi-and-friends-guess-what/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Didi and Friends, popular kids animation with over 1 billion views on Youtube is here with a brand new game. Guess the hidden character, then drag and drop the matching picture to reveal it. Teach your kids and toddlers to spot patterns, and get rewarded with happy smiles from Didi the Chicken and his friends! Features: - Fun and vibrant theme, guaranteed to excite kids, preschoolers and toddlers. - Simple gameplay suitable for kids - Fullscreen mode - Learn everyday objects, animals, environmental elements and above all, the brand new set of Didi and Friends characters!"
        },
        {
        plays: 7,
        language: "en",
        title: "Ludo With Friends",
        date_added: "06-21-2019",
        id: "5147075350102016",
        icon_large: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5147075350102016&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Classic multiplayer board game for family and friends",
        icon_small: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/ludo-with-friends/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Ludo with Friends is the modern version of the royal game of Pachisi. It's a game which was played among Indian kings and queens in ancient times. Roll the Ludo dice and move your tokens to reach the center of the Ludo board. Beat other opponents and become the king of Ludo in this multiplayer game. No complicated login screens. Just enter your username and play against the world. Play with your friends in a 2-player or 4-player mode. Features: - Chat with your friends in real-time - Feeling lazy? Use the autoplay function - Server side cheat detection - Play online against friends or offline against bots or computers"
        },
        {
        plays: 93,
        language: "en",
        title: "Trump Quiz",
        date_added: "12-01-2017",
        id: "4909832368816128",
        icon_large: "http://cdn.marketjs.net/games/trump-quiz/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/trump-quiz/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4909832368816128&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/trump-quiz/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/trump-quiz/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How well do you know Donald?",
        icon_small: "http://cdn.marketjs.net/games/trump-quiz/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/trump-quiz/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>How well do you know Donald? Embark on this quiz to find out more about your favorite celebrity</p> <p>Features:</p> <ul> <li>Extremely simple interface.</li> <li>Interesting facts</li> <li>Randomly generated questions</li> <li>Accuracy score</li> </ul>"
        },
        {
        plays: 8,
        language: "en",
        title: "Count Faster",
        date_added: "07-17-2018",
        id: "6505317405818880",
        icon_large: "http://cdn.marketjs.net/games/countfaster/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/countfaster/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6505317405818880&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/countfaster/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/countfaster/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How fast can you solve the math?",
        icon_small: "http://cdn.marketjs.net/games/countfaster/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/countfaster/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Here's the deal : solve the simple arithmetic questions before the time runs out. How fast does your brain work? Features: - extremely easy learnng curve - increasingly challenging levels. The further you progress, the shorter the time - fun and upbeat theme suitable for all ages - high score to keep tabs of your performance - a great way to test both math and reflex skills"
        },
        {
        plays: 11,
        language: "en",
        title: "Tower of Colors - Island Edition",
        date_added: "03-12-2021",
        id: "4905363112460288",
        icon_large: "http://subscription-cdn.marketjs.com/games/tower-of-colors-island-edition/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/tower-of-colors-island-edition/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4905363112460288&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/tower-of-colors-island-edition/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/tower-of-colors-island-edition/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Match colors to destroy tower blocks",
        icon_small: "http://subscription-cdn.marketjs.com/games/tower-of-colors-island-edition/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/tower-of-colors-island-edition/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Shoot balls to match the color of the tower blocks. Rotate the tower to find the best spots. Collect coins to use power ups such as wildcard and spinning lasers. Check back every day to collect your daily rewards. Features: - Island Edition with beautiful water and island scenery, surrounding the tower. - Endless gameplay with unlimited levels. - Chill and relaxing music. - Responsive 3D design. - Zoom in to get a better shooting angle."
        },
        {
        plays: 15,
        language: "en",
        title: "Super Bubble Shooter",
        date_added: "03-12-2021",
        id: "6693820998615040",
        icon_large: "http://subscription-cdn.marketjs.com/games/super-bubble-shooter/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/super-bubble-shooter/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6693820998615040&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/super-bubble-shooter/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/super-bubble-shooter/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Match bubbles of the same color",
        icon_small: "http://subscription-cdn.marketjs.com/games/super-bubble-shooter/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/super-bubble-shooter/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Pop 3 or more bubbles of the same color. Navigate around obstacles such as rock bubbles, glass bubbles and spikes. How many stars can you score for each level? Features - Use a variety of power ups such as bombs Rainbow bubbles, Thunder Strikes and Shields to achieve your objectives - Over 60 challenging levels in this classic bubble shooter game"
        },
        {
        plays: 5,
        language: "en",
        title: "Sudoku Village",
        date_added: "12-01-2017",
        id: "6049784653676544",
        icon_large: "http://cdn.marketjs.net/games/sudoku-village/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/sudoku-village/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6049784653676544&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/sudoku-village/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/sudoku-village/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "A classic sudoku game",
        icon_small: "http://cdn.marketjs.net/games/sudoku-village/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/sudoku-village/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>How good are your sudoku skills?</p> <p>In Sudoku, a 9x9 grid is given with any amount of numbers already filled in.</p> <p>To solve the puzzle, fill in the empty square with any number from 1- 9.</p> <p>The puzzle is complete when each row, each column and each 3x3 square within the puzzle contains the numbers 1-9, with each number appearing only once.</p> <p>Features:</p> <ul> <li>Calm and peaceful theme</li> <li>3 difficulty levels: Easy, Medium and Hard</li> <li>Unlimited puzzle generation, guaranteeing unlimited gameplay</li> </ul>"
        },
        {
        plays: 10,
        language: "en",
        title: "Car Park Puzzle",
        date_added: "07-17-2018",
        id: "4813538176532480",
        icon_large: "http://cdn.marketjs.net/games/car-park-puzzle/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/car-park-puzzle/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4813538176532480&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/car-park-puzzle/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/car-park-puzzle/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Move your car out of the parking lot",
        icon_small: "http://cdn.marketjs.net/games/car-park-puzzle/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/car-park-puzzle/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>What a parking mess! Find a way to move your car out of the parking lot.</p> <p>Features:</p> <ul> <li>Beautiful car parking lot</li> <li>24 challenging levels</li> <li>Feeling stuck? Use the hints system to help</li> </ul>"
        },
        {
        plays: 8,
        language: "en",
        title: "Jigsaw Puzzle Animal",
        date_added: "08-09-2019",
        id: "5632014842593280",
        icon_large: "http://cdn.marketjs.net/games/jigsaw-puzzle-animal/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/jigsaw-puzzle-animal/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5632014842593280&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/jigsaw-puzzle-animal/localization/en/media/graphics/promo/banners/1300x500.png",
        banner_medium: "http://cdn.marketjs.net/games/jigsaw-puzzle-animal/localization/en/media/graphics/promo/banners/440x280.png",
        short_description: "",
        icon_small: "http://cdn.marketjs.net/games/jigsaw-puzzle-animal/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/jigsaw-puzzle-animal/localization/en/media/graphics/promo/banners/180x120.png",
        long_description: ""
        },
        {
        plays: 7,
        language: "en",
        title: "Baby Cow Launcher",
        date_added: "12-01-2017",
        id: "6315703745380352",
        icon_large: "http://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6315703745380352&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Stop the greedy farmers. Launch baby cows!",
        icon_small: "http://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/baby-cow-launcher/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>The greedy farmers are milking cows for profit. As General Cow, your task is to disrupt these greedy farmers.</p> <p>Launch baby cows at greedy farmers to defeat them. Use a variety of power ups to win!</p> <p>Features:</p> <ul> <li>Baby cows with unique abilities</li> <li>Over 20 challenging levels</li> <li>Very cool physics terrain</li> <li>Challenging objects such as crates, glass, windmill, and more.</li> <li>Beautiful farm scenery</li> <li>Relaxing theme, suitable for an afternoon sit-down game session</li> </ul>"
        },
        {
        plays: 0,
        language: "en",
        title: "Spot The Patterns",
        date_added: "03-12-2021",
        id: "4817822417944576",
        icon_large: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4817822417944576&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Predict the next object intelligently",
        icon_small: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/spot-the-patterns/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A good cognitive training game. Predict the next object based on the previous pattern. Features: - Hint system - 3 different levels. Easy, Medium and Hard - Fun and vibrant theme which encourages learning This game is perfect for schools, preschool, families and even seniors."
        },
        {
        plays: 9,
        language: "en",
        title: "Chinese New Year Mahjong",
        date_added: "06-21-2019",
        id: "4911375765733376",
        icon_large: "http://cdn.marketjs.net/games/chinese-new-year-mahjong/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/chinese-new-year-mahjong/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4911375765733376&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/chinese-new-year-mahjong/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/chinese-new-year-mahjong/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Match mahjong tiles to win",
        icon_small: "http://cdn.marketjs.net/games/chinese-new-year-mahjong/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/chinese-new-year-mahjong/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Match chinese mahjong tiles to complete the levels. Features: - beautiful chinese inspired art - interactive tutorial - extremely simple and addictive gameplay - easy to start, hard to master - fun chinese / asian theme, coupled with mahjong matching elements - power ups to reward the user, such as auto solve bonuses"
        },
        {
        plays: 5,
        language: "en",
        title: "Sky High",
        date_added: "07-17-2018",
        id: "5752553654452224",
        icon_large: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5752553654452224&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/banners/1300x500.png",
        banner_medium: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/banners/440x280.png",
        short_description: "Build your tower sky high",
        icon_small: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/sky-high/localization/en/media/graphics/promo/banners/180x120.png",
        long_description: "How high can you build your tower? Use your timing to place the tower blocks correctly. Every inch of tower counts. Features: - Unlimited gameplay - Towers become more challenging to place as they get higher - Simple game controls: tap to place tower blocks - Use a variety of powerups such as Reverse, Repeat, Insurance, and Double Coins - Beautiful graphics and ancient greek theme"
        },
        {
        plays: 5,
        language: "en",
        title: "Guess The State USA Edition",
        date_added: "12-01-2017",
        id: "5693490809798656",
        icon_large: "http://cdn.marketjs.net/games/guess-the-state-usa-edition/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/guess-the-state-usa-edition/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5693490809798656&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/guess-the-state-usa-edition/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/guess-the-state-usa-edition/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Test your knowledge of the US",
        icon_small: "http://cdn.marketjs.net/games/guess-the-state-usa-edition/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/guess-the-state-usa-edition/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "How well do you know the USA? Test your knowledge of geography and history. Guess the correct US state based on limited information. Features: - Real USA map - Zoom in/out and pan the map to find your state - Interactive tutorial with female character - 3 Different modes - cities, capitals and landmarks - Statistics to show accuracy"
        },
        {
        plays: 5,
        language: "en",
        title: "Happy Hour",
        date_added: "03-12-2021",
        id: "4650211201777664",
        icon_large: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4650211201777664&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Fill up the glass",
        icon_small: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Fill up the martini glass. It's Happy Hour! Control the flow of drinks to fill up your glass! Everything you draw turns into real objects. Come up with your own solution to each level. Features: - Funny Happy Hour quotes. - Work on multiple drinks including cocktails, wine, spirits, beer and other alcohol related items. - Beautiful bar scene and nightlife theme - Chill vibe - Addictive tracing gameplay. Draw anything. - Over 30 challenging levels per city. Total of 120 levels. - Collect 3 stars for every level successfully completed. Fans of Happy Glass will enjoy this game."
        },
        {
        plays: 7,
        language: "en",
        title: "Memory Flex",
        date_added: "12-01-2017",
        id: "5668232056799232",
        icon_large: "http://cdn.marketjs.net/games/memory-flex/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/memory-flex/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5668232056799232&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/memory-flex/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/memory-flex/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Can you remember the pattern?",
        icon_small: "http://cdn.marketjs.net/games/memory-flex/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/memory-flex/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>How good is your memory? Play Memory Flex, a fun memory game.</p> <p>Improve your memory by remembering the green tiles in the matrix. Track your daily performance, and compare it with previous days.</p> <p>Features:</p> <ul> <li>crisp and fast animations</li> <li>increasingly difficult challenges</li> <li>a tutorial system</li> <li>a beautiful daily/weekly chart to analyze your performance</li> </ul>"
        },
        {
        plays: 13,
        language: "en",
        title: "Stick Golf",
        date_added: "07-17-2018",
        id: "5262430911332352",
        icon_large: "http://cdn.marketjs.net/games/stick-golf/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/stick-golf/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5262430911332352&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/stick-golf/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/stick-golf/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How good are your golf skills?",
        icon_small: "http://cdn.marketjs.net/games/stick-golf/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/stick-golf/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Aim, adjust the club power and go! Playing golf has never been this easy. From easy to challenging terrains, use your acute golf senses to land a hole in one. Avoid bunkers and water hazards! Features: - interactive tutorial to help your audience - relaxed theme and background. Playing golf has never been this relaxing. - earn coins from successful holes - use coins at the shop, to purchase fun skins such as top hat, pirate hat, bunny hats and more. "
        },
        {
        plays: 71,
        language: "en",
        title: "Tripoly",
        date_added: "09-16-2019",
        id: "5699318355853312",
        icon_large: "http://cdn.marketjs.net/games/tripoly/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/tripoly/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5699318355853312&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/tripoly/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/tripoly/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Rotate the triangle, to match the color of the line.",
        icon_small: "http://cdn.marketjs.net/games/tripoly/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/tripoly/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Rotate the triangle, to match the color of the line. How high can you score? Features: Fast and upbeat theme Interactive tutorial Easy to start, but it gets challenging very quickly"
        },
        {
        plays: 8,
        language: "en",
        title: "Puzzle Slide: Travel Edition",
        date_added: "09-16-2019",
        id: "5077274417168384",
        icon_large: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5077274417168384&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Discover your love of travelling",
        icon_small: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/puzzle-slide-travel-edition/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A picture slide game with a travel theme. Complete the puzzles in the shortest amount of time Solve puzzles of famous locations such as New York's Manhattan Bridge, The London Eye, Eiffel Tower of Paris, Forbidden City in Beijing, Tokyo Imperial Palace, Pyramids of Egypt, and more. Features - New-age, Instagram design for the millennial generation - Easy, medium and hard modes - Solve all kinds of puzzles from around the world - Simple design to encourage focus - Multiple puzzles to try - Relaxed environment "
        },
        {
        plays: 3,
        language: "en",
        title: "Picture Slider - Animals",
        date_added: "07-17-2018",
        id: "6548879581380608",
        icon_large: "http://cdn.marketjs.net/games/picture-slider-animals/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/picture-slider-animals/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6548879581380608&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/picture-slider-animals/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/picture-slider-animals/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Slide pictures of animals",
        icon_small: "http://cdn.marketjs.net/games/picture-slider-animals/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/picture-slider-animals/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Slide the tiles in the correct order, to complete the animal puzzles. How fast can you complete each puzzle? Features - 3 modes : easy, medium and hard - Animal specific theme containing cats, dogs, horses, elephants, ducks, birds, wildlife and more - Multiple puzzles to try - Relaxed environment designed for focus"
        },
        {
        plays: 113,
        language: "en",
        title: "Draw One Line",
        date_added: "09-16-2019",
        id: "5736463917383680",
        icon_large: "http://cdn.marketjs.net/games/draw-one-line/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/draw-one-line/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5736463917383680&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/draw-one-line/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/draw-one-line/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Connect dots without lifting a finger",
        icon_small: "http://cdn.marketjs.net/games/draw-one-line/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/draw-one-line/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Connect the dots to form a line, without ever lifting your finger or mouse. How many levels can you complete? Features: - Interactive tutorial - Over 120 challenging levels to keep you occupied - Fun theme - How difficult can this be? Just Draw 1 Line!"
        },
        {
        plays: 5,
        language: "en",
        title: "Mouse and Cheese",
        date_added: "12-01-2017",
        id: "6304594544033792",
        icon_large: "http://cdn.marketjs.net/games/mouse-and-cheese/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/mouse-and-cheese/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6304594544033792&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/mouse-and-cheese/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/mouse-and-cheese/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Move mouse to the cheese",
        icon_small: "http://cdn.marketjs.net/games/mouse-and-cheese/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/mouse-and-cheese/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Mouse needs cheese! Tap on the blocks, to clear them. Allow mouse to slide gracefully towards the cheese</p> <p>Features</p> <ul> <li>over 20 challenging levels! Each level requires specific planning and good finger-eye coordination, with increasingly difficult levels</li> <li>different objects to manipulate: blocks, bars, moving platforms, balls, and more!</li> <li>beautiful graphics, suitable for all ages</li> <li>fun music</li> <li>cute mouse</li> </ul>"
        },
        {
        plays: 6,
        language: "en",
        title: "Spades",
        date_added: "12-01-2017",
        id: "5769014806577152",
        icon_large: "http://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5769014806577152&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Classic spades card game",
        icon_small: "http://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/spades/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Play classic 4 player spades. Team up with an AI, make your bids and attempt to win the game. Spades is a fun card game involving strategy, probability and taking chances. Features - Blind nil function - Tutorial to explain the rules of the game - Bonus round for score ties - Casual relaxed environment for playing - Play against competent AI bots"
        },
        {
        plays: 61,
        language: "en",
        title: "Drone Pickup Service",
        date_added: "08-09-2019",
        id: "6291801544589312",
        icon_large: "http://cdn.marketjs.net/games/drone-pickup-service/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/drone-pickup-service/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6291801544589312&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/drone-pickup-service/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/drone-pickup-service/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Pick up packages for delivery",
        icon_small: "http://cdn.marketjs.net/games/drone-pickup-service/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/drone-pickup-service/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "The drone revolution has arrived. You operate a Drone pick up service. Your goal is to navigate the drones into difficult conditions, pick up the packages and return to base. Fly around trees, hills, cars, airplanes and wind mills to pick up your package. Complete your tasks in the fastest time to achieve 3 stars. Features: - easy left/right tapping mechanics to navigate - extremely challenging levels with various obstacles - Play with keyboard , mouse or touch - Fun theme and music, suitable for a techy audience who grows up with Uber, Amazon, Instacart and on-demand delivery services"
        },
        {
        plays: 6,
        language: "en",
        title: "Candy Christmas",
        date_added: "08-09-2019",
        id: "5641929338388480",
        icon_large: "http://cdn.marketjs.net/games/candy-christmas/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/candy-christmas/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5641929338388480&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/candy-christmas/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/candy-christmas/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Match christmas candy to win ",
        icon_small: "http://cdn.marketjs.net/games/candy-christmas/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/candy-christmas/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap and drag the christmas candy to switch positions. Match 3 or more of the same candy to score points. How many points can you score? Features: - Spend hours playing till your hearts content - Feeling stuck? Santa bombs to the rescue! Explode in a joy of laughter, ho ho ho. - Appetizing candy graphics - Fun theme and audio This is the season to celebrate xmas and spread the joy. "
        },
        {
        plays: 5,
        language: "en",
        title: "Learn Spanish Basic Skills",
        date_added: "12-01-2017",
        id: "5659089195499520",
        icon_large: "http://cdn.marketjs.net/games/learn-spanish-basic-skills/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/learn-spanish-basic-skills/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5659089195499520&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/learn-spanish-basic-skills/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/learn-spanish-basic-skills/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Learn spanish words, phrases and rules",
        icon_small: "http://cdn.marketjs.net/games/learn-spanish-basic-skills/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/learn-spanish-basic-skills/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Learn spanish fast. This HTML5 web app contains a variety of mini quizzes, such as image word association, basic sentence construction, word pairs, and more. The methods used are based on cognitive science and educational research psychology. They include active recall and spaced repetition. The questions adapt automatically to the user's performance. Features: - learn every day words such as everyday household objects, animals, people, fruits and more - easy transition between English and Spanish, while conditioning the brain to adjust via images, text and audio - relaxed theme - 3 big lesson themes, based on pronouns"
        },
        {
        plays: 4,
        language: "en",
        title: "Astrology Word Finder",
        date_added: "07-17-2018",
        id: "6193184214351872",
        icon_large: "http://cdn.marketjs.net/games/astrology-word-finder/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/astrology-word-finder/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6193184214351872&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/astrology-word-finder/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/astrology-word-finder/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Spot the words related to Astrology",
        icon_small: "http://cdn.marketjs.net/games/astrology-word-finder/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/astrology-word-finder/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>This game is for astrology buffs. How quickly can you spot the words?</p> <p>Click and drag the words to highlight them. Words can be highlighted forwards, vertically and also backwards.</p> <p>Includes words from themes such as zodiac signs, planets, chinese horoscope terms, measurement units and also famous astrologers.</p> <p>Features:</p> <ul> <li>Fun astrology theme</li> <li>3 different levels of difficulty (Easy, Medium and Hard)</li> <li>Expand your astrology vocabulary.</li> <li>Extremely high replayability</li> </ul>"
        },
        {
        plays: 21,
        language: "en",
        title: "Pack The Bag",
        date_added: "11-25-2015",
        id: "5643938803220480",
        icon_large: "http://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5643938803220480&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Use your spatial skills to pack the bag ",
        icon_small: "http://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://whitelabel-cdn.marketjs.com/games/pack-the-bag/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>How good are you at organizing things in confined spaces? Play Pack the Bag, a fun game to train your spatial skills.</p> <p>Improve your spatial skills by placing the item correctly in the bag. Track your daily performance, and compare it with previous days.</p> <p>Features:</p> <ul> <li>crisp and fast animations</li> <li>increasingly difficult challenges</li> <li>a tutorial system</li> <li>a beautiful daily/weekly chart to analyze your performance</li> </ul>"
        },
        {
        plays: 9,
        language: "en",
        title: "Rainbow Stacker",
        date_added: "07-17-2018",
        id: "5206197995044864",
        icon_large: "http://cdn.marketjs.net/games/rainbow-stacker/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/rainbow-stacker/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5206197995044864&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/rainbow-stacker/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/rainbow-stacker/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "How high can you stack the blocks?",
        icon_small: "http://cdn.marketjs.net/games/rainbow-stacker/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/rainbow-stacker/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>In this zen environment, how high can you stack the blocks?</p> <p>Marvel at your tower of blocks, glistening in rainbow colors.</p> <p>Features:</p> <ul> <li>Impressive rainbow coloration of each block</li> <li>Extremely simple, one-touch gameplay</li> <li>High score and combo score recording</li> <li>Easy to start playing, hard to master</li> </ul>"
        },
        {
        plays: 10,
        language: "en",
        title: "Adventure Craft",
        date_added: "07-17-2018",
        id: "5376940124930048",
        icon_large: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5376940124930048&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Mine similar blocks to score points",
        icon_small: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/adventure-craft/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Match similar blocks within the allocated time to progress. Click and drag to form giant blockchains.</p> <p>If you like voxels and minecraft, then this game is definitely for you.</p> <p>Features:</p> <ul> <li>Voxel based match 3 theme</li> <li>Innovative click and drag mechanic to build giant block chains</li> <li>20 challenging levels</li> <li>Tutorial to learn the ropes</li> <li>Good game pace and music</li> </ul>"
        },
        {
        plays: 24,
        language: "en",
        title: "Nom Nom Yum",
        date_added: "12-26-2019",
        id: "5507811686481920",
        icon_large: "http://subscription-cdn.marketjs.com/games/nom-nom-yum/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/nom-nom-yum/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5507811686481920&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/nom-nom-yum/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/nom-nom-yum/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Feed the hungry monster with sushi",
        icon_small: "http://subscription-cdn.marketjs.com/games/nom-nom-yum/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/nom-nom-yum/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "A sushi monster called Nom Nom descended onto Earth. It's really hungry for some good sushi. It's your job to feed Nom Nom at the Japanese restaurant. Swipe to cut the rope. Watch as the rope swings its way into the Nom Nom's mouth. Make it say YUM! Collect 3 stars in each level to score the maximum points. Features: - Calm, zen theme at a sushi restaurant - Story based animation - Fun rope slicing mechanics - Over 25 challenging levels - Interactive tutorial"
        },
        {
        plays: 6,
        language: "en",
        title: "Seashore Treasure",
        date_added: "03-12-2021",
        id: "6651232438452224",
        icon_large: "http://subscription-cdn.marketjs.com/games/seashore-treasure/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/seashore-treasure/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6651232438452224&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/seashore-treasure/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/seashore-treasure/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "A memory training game",
        icon_small: "http://subscription-cdn.marketjs.com/games/seashore-treasure/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/seashore-treasure/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Tap an item to pick it up. Next, pick up a new item that you haven't picked up before. Continue doing so, until you reach the limit. Pick up cool items such as sun shades, sea shells, turtles, jellyfish, shorts, sun screen, fish, seahorses and more. Features: - Fun, relaxed beach and sunny theme - Measure your cognitive ability and improve your memory - 3 different beaches - Beautiful sea shore graphics and animation"
        },
        {
        plays: 8,
        language: "en",
        title: "What's My Icon?",
        date_added: "12-01-2017",
        id: "5755290557349888",
        icon_large: "http://cdn.marketjs.net/games/whats-my-icon/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://cdn.marketjs.net/games/whats-my-icon/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5755290557349888&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://cdn.marketjs.net/games/whats-my-icon/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://cdn.marketjs.net/games/whats-my-icon/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Can you guess the icons?",
        icon_small: "http://cdn.marketjs.net/games/whats-my-icon/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://cdn.marketjs.net/games/whats-my-icon/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "<p>Can you guess the icons?</p> <p>Features:</p> <ul> <li>over 60 different icons</li> <li>guess brands, cities, famous people, characters and countries!</li> <li>randomized icon each time</li> <li>ability to solve puzzles, or remove letters.</li> </ul>"
        },
        {
        plays: 11,
        language: "en",
        title: "Cookie Line",
        date_added: "03-12-2021",
        id: "6510494950096896",
        icon_large: "http://subscription-cdn.marketjs.com/games/cookie-line/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/cookie-line/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6510494950096896&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/cookie-line/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/cookie-line/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Complete the lines in this hexagon cookie puzzle",
        icon_small: "http://subscription-cdn.marketjs.com/games/cookie-line/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/cookie-line/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Drag and drop the hexagon pieces onto empty slots. Create full lines to eliminate the tiles. What's your highest score? Features: - Fun and cute theme, to induce focus - Score combo points by clearing 2 or more lines simultaneously"
        }
]