export const RECOMMENDEDGAMES = [
                {
                genres: "Family,Puzzle",
                screenshot2_small: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 9,
                language: "en",
                title: "Pattern Flex",
                date_added: "12-01-2017",
                id: "5129511356071936",
                screenshot1_small: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5129511356071936&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Can you remember the patterns?",
                icon_small: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>How good is your memory? Play Pattern Flex, a fun memory game for the family.</p> <p>Improve your memory with multiple shapes. Track your daily performance, and compare it with previous days.</p> <p>Features:</p> <ul> <li>crisp and fast animations</li> <li>a tutorial system</li> <li>a beautiful daily/weekly chart to analyze your performance</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/pattern-flex/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action",
                screenshot2_small: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 10,
                language: "en",
                title: "Defend The Tank",
                date_added: "12-01-2017",
                id: "5733575152369664",
                screenshot1_small: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5733575152369664&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Manage soldiers to protect your tank",
                icon_small: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "Control a team of tough soldiers. Drag and drop soldiers to place them at strategic positions on the tank. Keep the tank alive at all costs. Rotate your soldiers to inflict maximum damage on the enemy. Heal your tanks with mechanic soldiers. Collect coins to upgrade your tank after each battle. Unlock special soldier classes. Features: - Innovative drag and drop mechanic: Drag and place soldiers onto strategic positions on your tank. - Unlimited waves of enemies. They come with tanks, jeeps, airships and yes, battlecruisers. - Different soldier classes to play with. Control infantry, mechanics, rocket men, and machine gunners - Exciting theme and music - Interactive tutorial",
                screenshot3_small: "https://cdn.marketjs.net/games/defend-the-tank/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Adventure,Action",
                screenshot2_small: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 28,
                language: "en",
                title: "Escape From Aztec",
                date_added: "12-01-2017",
                id: "5666825723445248",
                screenshot1_small: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5666825723445248&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Run fast, avoid being caught",
                icon_small: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "You just stole King Aztec's greatest treasure. Now you're being hunted. Run as fast as you can. Avoid tree trunks, boulders and ancient ruins. Switch lanes, jump and slide your way to freedom. Collect treasures along the way to purchase powerups. How far can you escape? Features: - 3D-like environment built with Aztec theme - Use Aztec coins to purchase powerups in the store - Use a variety of powerups such as invincibility, coin magnets, megaboost and extra lives",
                screenshot3_small: "https://cdn.marketjs.net/games/escape-from-aztec/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family",
                screenshot2_small: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 4,
                language: "en",
                title: "Count Faster",
                date_added: "12-01-2017",
                id: "5156545222410240",
                screenshot1_small: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5156545222410240&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "How fast can you solve the math?",
                icon_small: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Here's the deal : solve the simple arithmetic questions before the time runs out. How fast does your brain work?</p> <p>Features:</p> <ul> <li>extremely easy learnng curve</li> <li>increasingly challenging levels. The further you progress, the shorter the time</li> <li>fun and upbeat theme suitable for all ages</li> <li>high score to keep tabs of your performance</li> <li>a great way to test both math and reflex skills</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/count-faster/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action,Adventure",
                screenshot2_small: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 29,
                language: "en",
                title: "Shark Attack",
                date_added: "12-01-2017",
                id: "5662200312102912",
                screenshot1_small: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5662200312102912&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Live the life of a hungry shark",
                icon_small: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Have you ever wondered what the life of a shark is like? Now you can live it. Swim around the ocean and hunt for your prey. Balance other aspects such as health, air and hunger. Avoid the jellyfish, bombs and fishing nets!</p> <p>A fun game for everyone, giving hours of gameplay.</p> <p>Features:</p> <ul> <li>Hunt other marine animals, including fish, octopus, starfish, crabs, and more</li> <li>Collect powerups for health, booster and energy</li> <li>Fun elements : attack boats, ships, divers and more</li> <li>Avoid the jelly fish, bombs and fishing nets</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/shark-attack/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action",
                screenshot2_small: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 7,
                language: "en",
                title: "Leave Me Alone",
                date_added: "12-01-2017",
                id: "5097665247313920",
                screenshot1_small: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5097665247313920&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Don't let the zombies touch you!",
                icon_small: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Play as a martial arts master, and fend of incoming zombies from all directions. How long can you last? It gets increasingly difficult in the later stages!</p> <p>Use the swipe method (mobile) and keyboard arrows (desktop).</p> <p>Features:</p> <ul> <li>tutorial provided</li> <li>tons of zombies</li> <li>unlimited gameplay</li> <li>fun music</li> <li>unlock cool characters by scoring more points</li> <li>play as different characters : Ninja, Mr. Lee, Ironbot, Samurai and more!</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/leave-me-alone/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action,Family",
                screenshot2_small: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 5,
                language: "en",
                title: "Paper Flick",
                date_added: "12-01-2017",
                id: "5720928352731136",
                screenshot1_small: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/candy-slide/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5720928352731136&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Flick the paper ball into the basket",
                icon_small: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Aim and throw the paper ball into the basket. How accurate are you?</p> <p>Features:</p> <ul> <li>Choose from 3 difficulties: easy, medium and hard</li> <li>Fun office environment. It's just perfect for killing time.</li> <li>Funny sound effects</li> <li>Local high score for keeping track of your winning streaks</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/paper-flick/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Family",
                screenshot2_small: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 5,
                language: "en",
                title: "Math Genius",
                date_added: "12-01-2017",
                id: "5747275024302080",
                screenshot1_small: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5747275024302080&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "How fast can you solve the math quizzes?",
                icon_small: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "How fast can you solve the math? Add, subtract, multiply and divide your way to the highest score. Features - Tutorial ready - Distraction free user interface - Cute characters, suitable for a younger audience - Fun music and theme",
                screenshot3_small: "https://cdn.marketjs.net/games/math-genius/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Adventure,Action",
                screenshot2_small: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 46,
                language: "en",
                title: "Hidden Objects - Mysterious Artifacts",
                date_added: "12-01-2017",
                id: "5133511581237248",
                screenshot1_small: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5133511581237248&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Search for mysterious hidden artifacts",
                icon_small: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "<p>Billy the Treasure Hunter is back! Help Billy uncover ancient artifacts in this hidden object game. Discover beautiful hidden objects in different settings.</p> <p> Features: </p> <ul> <li>Mysterious ancient theme</li> <li>Over 50 objects to discover - Jewels, ancient scrolls, magic staffs and more</li> <li>Need help? Use hints by earning hints points (keys)</li> <li>Complete tutorial system</li> <li>Over 9 challenging levels in 3 different settings</li> </ul>",
                screenshot3_small: "https://cdn.marketjs.net/games/hidden-objects-mysterious-artifacts/localization/en/media/graphics/promo/screenshots/3.jpg"
                },
                {
                genres: "Action,Sports",
                screenshot2_small: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/screenshots/2.jpg",
                plays: 31,
                language: "en",
                title: "Super Boxing - Fight Night",
                date_added: "12-01-2017",
                id: "5711257965428736",
                screenshot1_small: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/screenshots/1.jpg",
                icon_large: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/icons/128x128.png",
                icon_medium: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/icons/96x96.png",
                featured: "false",
                url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5711257965428736&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200",
                banner_large: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/banners/1300x500.jpg",
                banner_medium: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/banners/440x280.jpg",
                short_description: "Box your way to glory",
                icon_small: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/icons/64x64.png",
                banner_small: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/banners/180x120.jpg",
                long_description: "Box your way to glory! Throw jabs and crosses. Block punches with your boxing gloves. Try not to get KO'ed by your opponent. This is a great game if you are athletic. Features: - Increasingly clever opponents - Entertaining fights! - Simple one-touch gameplay - Gain powerups from combinations - Train to be a great boxer and athlete.",
                screenshot3_small: "https://cdn.marketjs.net/games/super-boxing/localization/en/media/graphics/promo/screenshots/3.jpg"
                }
]