export const STRATEGYGAMES = [
        {
        plays: 6,
        language: "en",
        title: "Unblocked",
        date_added: "03-12-2021",
        id: "6617265404379136",
        icon_large: "http://subscription-cdn.marketjs.com/games/unblocked/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/unblocked/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6617265404379136&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/unblocked/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/unblocked/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Release the red tile",
        icon_small: "http://subscription-cdn.marketjs.com/games/unblocked/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/unblocked/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Clear a path for the red block. How many moves do you need, to win? Features: - Bright and positive theme - 24 challenging levels - Interactive hint system to help solve the puzzle"
        },
        {
        plays: 5,
        language: "en",
        title: "Happy Hour",
        date_added: "03-12-2021",
        id: "4650211201777664",
        icon_large: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4650211201777664&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Fill up the glass",
        icon_small: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/happy-hour/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Fill up the martini glass. It's Happy Hour! Control the flow of drinks to fill up your glass! Everything you draw turns into real objects. Come up with your own solution to each level. Features: - Funny Happy Hour quotes. - Work on multiple drinks including cocktails, wine, spirits, beer and other alcohol related items. - Beautiful bar scene and nightlife theme - Chill vibe - Addictive tracing gameplay. Draw anything. - Over 30 challenging levels per city. Total of 120 levels. - Collect 3 stars for every level successfully completed. Fans of Happy Glass will enjoy this game."
        },
        {
        plays: 0,
        language: "en",
        title: "Horace Vs Cheese",
        date_added: "03-12-2021",
        id: "5712878653931520",
        icon_large: "http://subscription-cdn.marketjs.com/games/horace-vs-cheese/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/horace-vs-cheese/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5712878653931520&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/horace-vs-cheese/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/horace-vs-cheese/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Launch Horace the Hamster into the cheese!",
        icon_small: "http://subscription-cdn.marketjs.com/games/horace-vs-cheese/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/horace-vs-cheese/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Pull and launch Horace the Hamster into the cheese. Eat them all to earn 3 stars. Then, land safely into the cheese house. From the creators of Flossy and Jim, we bring you a new brand called Horace and co. Features: - Fun, positive and ridiculously cute character. Horace bounces around and squeals almost like a soft toy. - Innovative touch and drag mechanic - Over 30 levels - Unlock a hidden level - Don't eat the blue cheese! You'll lose a life - Don't eat the moldy cheese! You'll lose the level"
        },
        {
        plays: 3,
        language: "en",
        title: "Hogie the Globehopper Adventure Puzzle",
        date_added: "03-12-2021",
        id: "6514598506135552",
        icon_large: "http://subscription-cdn.marketjs.com/games/hogie-the-globehopper-adventure-puzzle/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/hogie-the-globehopper-adventure-puzzle/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6514598506135552&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/hogie-the-globehopper-adventure-puzzle/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/hogie-the-globehopper-adventure-puzzle/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Drag and drop blocks to form paths",
        icon_small: "http://subscription-cdn.marketjs.com/games/hogie-the-globehopper-adventure-puzzle/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/hogie-the-globehopper-adventure-puzzle/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Hogie The Globehopper is a world-renowned kids animation brand on Netflix and cable TV. Now, you can play a Hogie branded game! Drag and drop blocks to form a path, for Hogie to cross. Collect 3 stars and a banana, to complete the level. Solve puzzles while travelling different cities of the world, including Bangkok, Barcelona, Cairo, and Machu Pichu. Features: - Highly interactive tutorial with voiceover - Over 80 challenging levels to train cognitive ability - Fun and pleasant theme for kids and parents - Discover new in-game mechanics to interact with, such as ladders, trampolines and fans."
        },
        {
        plays: 8,
        language: "en",
        title: "Poker with Buddies",
        date_added: "03-12-2021",
        id: "4947100933554176",
        icon_large: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4947100933554176&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Texas hold em poker with friends",
        icon_small: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/poker-with-buddies/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Play Texas Hold 'Em poker with anyone on the internet. Place virtual chips on the table, and try to outsmart the other players and the dealer. Meet new friends online over casual poker games. Want to only play with your friends? No problem. Set up a private room with a password. Features: - Up to 6 players in a room - Unlimited rooms - Chat functionality - Play if bots or AI, if humans are not present - Automatic room assignment - Private rooms with password is now possible - Pick a cool avatar before joining the room Fans of Texas Holdem Poker will appreciate this game."
        },
        {
        plays: 7,
        language: "en",
        title: "Crazy Truck Parking",
        date_added: "03-12-2021",
        id: "4836064888881152",
        icon_large: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=4836064888881152&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Attempt to park your truck, with precision.",
        icon_small: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/crazy-truck-parking/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Truck parking simulator game. It's easy to learn, and yet incredibly difficult to master. Park your truck in the perfect spot, with surgical precision. Be careful not to bump into other trucks and obstacles. Fasten your safety belt, and let the game begin! Fans of parking frenzy games will love this. Features: - Interactive tutorial - Beautiful parking spots - 3 Star based system to reward precision - Over 50+ parking challenges - Keyboard controls for desktop, and touch controls for smartphones and tablets - Drive a variety of cool cars"
        },
        {
        plays: 2,
        language: "en",
        title: "Battleships Ready Go!",
        date_added: "03-12-2021",
        id: "5683524616060928",
        icon_large: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5683524616060928&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Sink the enemy ships in naval warfare",
        icon_small: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/battleships-ready-go/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Battleships Ready Go is a guessing war game. Place your ships strategically across the open sea. Then, try to sink the enemy ships, before own own navy ships are sunk. Features: - Interactive tutorial - Fast paced music and gameplay - Millions of battleship arrangements, for hours of gameplay - Clever AI to compete against"
        },
        {
        plays: 2,
        language: "en",
        title: "Cat Wizard Defense",
        date_added: "03-12-2021",
        id: "5632254735810560",
        icon_large: "http://subscription-cdn.marketjs.com/games/cat-wizard-defense/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/cat-wizard-defense/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5632254735810560&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/cat-wizard-defense/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/cat-wizard-defense/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Defend your cat base against slime invaders",
        icon_small: "http://subscription-cdn.marketjs.com/games/cat-wizard-defense/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/cat-wizard-defense/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Position the cat defensive towers to defend against slime balls. Collect energy by destroying the slime balls. Use energy to purchase better towers. Don't let the slime balls reach your base! Features - Interactive tutorial - Great animal theme - 18 large, challenging levels - A variety of slime monsters are unlocked as you progress. Use them strategically to win each level"
        }
        
]