export const WORDGAMES = [
        {
        plays: 1,
        language: "en",
        title: "Typing Fighter",
        date_added: "03-12-2021",
        id: "6749550397095936",
        icon_large: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6749550397095936&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Type fast and fight hard",
        icon_small: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/typing-fighter/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Type fast, type accurate and fight hard in this innovative street fighter style typing game. Charge up your typing and deliver killer power moves. Get inspired by motivational phrases and quotes while you type. Fight against a variety of opponents. Features: - Beautifully designed street fight urban setting - Fluid character animations - Over 200 motivational quotes and phrases to keep you going"
        },
        {
        plays: 8,
        language: "en",
        title: "Wheel of Rewards",
        date_added: "03-12-2021",
        id: "5286446115061760",
        icon_large: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=5286446115061760&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Spin the wheel, guess the letter and solve the puzzle",
        icon_small: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/wheel-of-rewards/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Spin the wheel, guess letter and solve the puzzle! Earn cash from your spins, to purchase more vowels. Uncover the puzzle letter by letter, and solve it to win bonus rewards. Try not to go bankrupt or run out of lives! Your fortune depends on your ability to solve the puzzle. Answer questions from a variety of topics such as: - Things People Worry About - What People Do At 3 AM - What Happens At Work - Special Occasions - Common Excuses to Skip Work and many other thought-provoking topics! Features: - Vibrant and fresh game show theme - Over 200 puzzles to solve - 10 lives to start with - Full screen mode"
        },
        {
        plays: 1,
        language: "en",
        title: "Holiday Crossword",
        date_added: "03-12-2021",
        id: "6498977928183808",
        icon_large: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/128x128.png",
        icon_medium: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/96x96.png",
        url: "https://subscription.marketjs.com/serve?portal_id=5692266857365504&game_id=6498977928183808&branding_id=5169425925799936&ad_id=5185095820378112&portal_localization_id=6207741047603200&clear_cache=yes",
        banner_large: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/1300x500.jpg",
        banner_medium: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/440x280.jpg",
        short_description: "Travel and learn while solving crossword puzzles.",
        icon_small: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/icons/64x64.png",
        banner_small: "http://subscription-cdn.marketjs.com/games/holiday-crossword/localization/en/media/graphics/promo/banners/180x120.jpg",
        long_description: "Solve holiday themed crossword puzzles involving various topics such as cities, food, celebrations and gift ideas. Features: - Full screen mode - Easy to use cross word puzzle. Regardless of device, play the same crossword puzzle as everybody else - Easy selection of puzzle grid to insert answers - Virtual keyboard for mobile and tablet users. Easily enter your answers to solve the puzzles - Random puzzles generated from a pool of questions and answers - Relaxing theme, suitable for everyone Note: if you'd like different themes and questions, please contact us."
        }
]